# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project/lookup/user/user_lookup_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from project.lookup.user import user_lookup_pb2 as project_dot_lookup_dot_user_dot_user__lookup__pb2
import order_pb2 as order__pb2
import filter_pb2 as filter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='project/lookup/user/user_lookup_app_service.proto',
  package='cafm.project.lookup.user',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1project/lookup/user/user_lookup_app_service.proto\x12\x18\x63\x61\x66m.project.lookup.user\x1a%project/lookup/user/user_lookup.proto\x1a\x0border.proto\x1a\x0c\x66ilter.proto\"B\n1UserLookupAppService_userLookupByUserEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"o\n2UserLookupAppService_userLookupByUserEmailResponse\x12\x39\n\x0buser_lookup\x18\x01 \x01(\x0b\x32$.cafm.project.lookup.user.UserLookup\"<\n.UserLookupAppService_userLookupByUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"l\n/UserLookupAppService_userLookupByUserIdResponse\x12\x39\n\x0buser_lookup\x18\x01 \x01(\x0b\x32$.cafm.project.lookup.user.UserLookup\"\xaa\x01\n\'UserLookupAppService_userLookupsRequest\x12\x13\n\x0bresult_from\x18\x01 \x01(\x05\x12\x13\n\x0bresult_size\x18\x02 \x01(\x05\x12(\n\x06orders\x18\x03 \x03(\x0b\x32\x18.cafm.common.order.Order\x12+\n\x07\x66ilters\x18\x04 \x03(\x0b\x32\x1a.cafm.common.filter.Filter\"\x80\x01\n(UserLookupAppService_userLookupsResponse\x12:\n\x0cuser_lookups\x18\x01 \x03(\x0b\x32$.cafm.project.lookup.user.UserLookup\x12\x18\n\x10total_item_count\x18\x02 \x01(\x05\x32\x97\x04\n\x14UserLookupAppService\x12\xb8\x01\n\x19user_lookup_by_user_email\x12K.cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailRequest\x1aL.cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailResponse\"\x00\x12\xaf\x01\n\x16user_lookup_by_user_id\x12H.cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdRequest\x1aI.cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdResponse\"\x00\x12\x91\x01\n\x06lookup\x12\x41.cafm.project.lookup.user.UserLookupAppService_userLookupsRequest\x1a\x42.cafm.project.lookup.user.UserLookupAppService_userLookupsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[project_dot_lookup_dot_user_dot_user__lookup__pb2.DESCRIPTOR,order__pb2.DESCRIPTOR,filter__pb2.DESCRIPTOR,])




_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILREQUEST = _descriptor.Descriptor(
  name='UserLookupAppService_userLookupByUserEmailRequest',
  full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=211,
)


_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILRESPONSE = _descriptor.Descriptor(
  name='UserLookupAppService_userLookupByUserEmailResponse',
  full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_lookup', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailResponse.user_lookup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=324,
)


_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDREQUEST = _descriptor.Descriptor(
  name='UserLookupAppService_userLookupByUserIdRequest',
  full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=386,
)


_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDRESPONSE = _descriptor.Descriptor(
  name='UserLookupAppService_userLookupByUserIdResponse',
  full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_lookup', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdResponse.user_lookup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=496,
)


_USERLOOKUPAPPSERVICE_USERLOOKUPSREQUEST = _descriptor.Descriptor(
  name='UserLookupAppService_userLookupsRequest',
  full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_from', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsRequest.result_from', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_size', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsRequest.result_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orders', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsRequest.orders', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filters', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsRequest.filters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=669,
)


_USERLOOKUPAPPSERVICE_USERLOOKUPSRESPONSE = _descriptor.Descriptor(
  name='UserLookupAppService_userLookupsResponse',
  full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_lookups', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsResponse.user_lookups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_item_count', full_name='cafm.project.lookup.user.UserLookupAppService_userLookupsResponse.total_item_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=672,
  serialized_end=800,
)

_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILRESPONSE.fields_by_name['user_lookup'].message_type = project_dot_lookup_dot_user_dot_user__lookup__pb2._USERLOOKUP
_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDRESPONSE.fields_by_name['user_lookup'].message_type = project_dot_lookup_dot_user_dot_user__lookup__pb2._USERLOOKUP
_USERLOOKUPAPPSERVICE_USERLOOKUPSREQUEST.fields_by_name['orders'].message_type = order__pb2._ORDER
_USERLOOKUPAPPSERVICE_USERLOOKUPSREQUEST.fields_by_name['filters'].message_type = filter__pb2._FILTER
_USERLOOKUPAPPSERVICE_USERLOOKUPSRESPONSE.fields_by_name['user_lookups'].message_type = project_dot_lookup_dot_user_dot_user__lookup__pb2._USERLOOKUP
DESCRIPTOR.message_types_by_name['UserLookupAppService_userLookupByUserEmailRequest'] = _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILREQUEST
DESCRIPTOR.message_types_by_name['UserLookupAppService_userLookupByUserEmailResponse'] = _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILRESPONSE
DESCRIPTOR.message_types_by_name['UserLookupAppService_userLookupByUserIdRequest'] = _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDREQUEST
DESCRIPTOR.message_types_by_name['UserLookupAppService_userLookupByUserIdResponse'] = _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDRESPONSE
DESCRIPTOR.message_types_by_name['UserLookupAppService_userLookupsRequest'] = _USERLOOKUPAPPSERVICE_USERLOOKUPSREQUEST
DESCRIPTOR.message_types_by_name['UserLookupAppService_userLookupsResponse'] = _USERLOOKUPAPPSERVICE_USERLOOKUPSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserLookupAppService_userLookupByUserEmailRequest = _reflection.GeneratedProtocolMessageType('UserLookupAppService_userLookupByUserEmailRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILREQUEST,
  '__module__' : 'project.lookup.user.user_lookup_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailRequest)
  })
_sym_db.RegisterMessage(UserLookupAppService_userLookupByUserEmailRequest)

UserLookupAppService_userLookupByUserEmailResponse = _reflection.GeneratedProtocolMessageType('UserLookupAppService_userLookupByUserEmailResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILRESPONSE,
  '__module__' : 'project.lookup.user.user_lookup_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.project.lookup.user.UserLookupAppService_userLookupByUserEmailResponse)
  })
_sym_db.RegisterMessage(UserLookupAppService_userLookupByUserEmailResponse)

UserLookupAppService_userLookupByUserIdRequest = _reflection.GeneratedProtocolMessageType('UserLookupAppService_userLookupByUserIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDREQUEST,
  '__module__' : 'project.lookup.user.user_lookup_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdRequest)
  })
_sym_db.RegisterMessage(UserLookupAppService_userLookupByUserIdRequest)

UserLookupAppService_userLookupByUserIdResponse = _reflection.GeneratedProtocolMessageType('UserLookupAppService_userLookupByUserIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDRESPONSE,
  '__module__' : 'project.lookup.user.user_lookup_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.project.lookup.user.UserLookupAppService_userLookupByUserIdResponse)
  })
_sym_db.RegisterMessage(UserLookupAppService_userLookupByUserIdResponse)

UserLookupAppService_userLookupsRequest = _reflection.GeneratedProtocolMessageType('UserLookupAppService_userLookupsRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERLOOKUPAPPSERVICE_USERLOOKUPSREQUEST,
  '__module__' : 'project.lookup.user.user_lookup_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.project.lookup.user.UserLookupAppService_userLookupsRequest)
  })
_sym_db.RegisterMessage(UserLookupAppService_userLookupsRequest)

UserLookupAppService_userLookupsResponse = _reflection.GeneratedProtocolMessageType('UserLookupAppService_userLookupsResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERLOOKUPAPPSERVICE_USERLOOKUPSRESPONSE,
  '__module__' : 'project.lookup.user.user_lookup_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.project.lookup.user.UserLookupAppService_userLookupsResponse)
  })
_sym_db.RegisterMessage(UserLookupAppService_userLookupsResponse)



_USERLOOKUPAPPSERVICE = _descriptor.ServiceDescriptor(
  name='UserLookupAppService',
  full_name='cafm.project.lookup.user.UserLookupAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=803,
  serialized_end=1338,
  methods=[
  _descriptor.MethodDescriptor(
    name='user_lookup_by_user_email',
    full_name='cafm.project.lookup.user.UserLookupAppService.user_lookup_by_user_email',
    index=0,
    containing_service=None,
    input_type=_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILREQUEST,
    output_type=_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSEREMAILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='user_lookup_by_user_id',
    full_name='cafm.project.lookup.user.UserLookupAppService.user_lookup_by_user_id',
    index=1,
    containing_service=None,
    input_type=_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDREQUEST,
    output_type=_USERLOOKUPAPPSERVICE_USERLOOKUPBYUSERIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='lookup',
    full_name='cafm.project.lookup.user.UserLookupAppService.lookup',
    index=2,
    containing_service=None,
    input_type=_USERLOOKUPAPPSERVICE_USERLOOKUPSREQUEST,
    output_type=_USERLOOKUPAPPSERVICE_USERLOOKUPSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERLOOKUPAPPSERVICE)

DESCRIPTOR.services_by_name['UserLookupAppService'] = _USERLOOKUPAPPSERVICE

# @@protoc_insertion_point(module_scope)
