---

globals:
  paths:
    application: 'src/application'
    domain_model: 'src/domain_model'
    exception: 'src/domain_model/resource/exception'
    port_adapter: 'src/port_adapter'
    repository: 'src/port_adapter/repository'
    db_model: 'src/port_adapter/repository/db_model'
    messaging_listener: 'src/port_adapter/messaging/listener'
    grpc_api_listener: 'src/port_adapter/api/grpc/listener'
    proto_buffer: 'src/resource/proto'

domain_models:
  - model:
      skip: [model, app_service, repository_impl, db_repository, listener, proto, grcp]
      path: laptop
      name: laptop
      fields:
        - name: name
          type: str
          default: None
          db:
            type: 'String(40)'
            extra: "ForeignKey('building.id'), nullable=False"
          proto:
            type: string
        - name: web_url
          type: str
          default: None
          db:
            type: 'String(40)'
          proto:
            type: string
  - model:
      path: laptop/newone
      name: laptop2
      fields:
        - name: name
          type: str
          default: None
          db:
            type: 'String(40)'
          proto:
            type: string
        - name: quantity
          type: int
          default: -1
          db:
            type: 'Integer'
          proto:
            type: int32
  - model:
      path: laptop/newone2
      name: laptop_very_good
      fields:
        - name: name
          type: str
          default: None
          db:
            type: 'String(40)'
          proto:
            type: string
        - name: quantity
          type: int
          default: None
          db:
            type: 'Integer'
          proto:
            type: int32