"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""



import grpc

from src.application.MaintenanceProcedureOperationApplicationService import MaintenanceProcedureOperationApplicationService
from src.domain_model.project.maintenance.procedure.operation.MaintenanceProcedureOperation import MaintenanceProcedureOperation
from src.domain_model.resource.exception.MaintenanceProcedureOperationDoesNotExistException import MaintenanceProcedureOperationDoesNotExistException
from src.domain_model.resource.exception.UnAuthorizedException import UnAuthorizedException
from src.port_adapter.api.grpc.listener.CommonBaseListener import CommonBaseListener
from src.resource.logging.decorator import debugLogger
from src.resource.logging.opentelemetry.OpenTelemetry import OpenTelemetry
from src.resource.proto._generated.maintenance_procedure_operation_app_service_pb2 import (
    MaintenanceProcedureOperationAppService_maintenanceProcedureOperationsResponse,
    MaintenanceProcedureOperationAppService_maintenanceProcedureOperationByIdResponse,
    MaintenanceProcedureOperationAppService_newIdResponse,
    MaintenanceProcedureOperationAppService_maintenanceProcedureOperationsByMaintenanceProcedureIdResponse,
)
from src.resource.proto._generated.maintenance_procedure_operation_app_service_pb2_grpc import (
    MaintenanceProcedureOperationAppServiceServicer,
)

class MaintenanceProcedureOperationAppServiceListener(
    CommonBaseListener, MaintenanceProcedureOperationAppServiceServicer
):
    """The listener function implements the rpc call as described in the .proto file"""
    def __init__(self):
        super().__init__()
        import src.port_adapter.AppDi as AppDi
        self._appService: MaintenanceProcedureOperationApplicationService = AppDi.instance.get(
            MaintenanceProcedureOperationApplicationService
        )


    def __str__(self):
        return self.__class__.__name__

    @debugLogger
    @OpenTelemetry.grpcTraceOTel
    def new_id(self, request, context):
        return super().newId(request=request, context=context, response=MaintenanceProcedureOperationAppService_newIdResponse)


    @debugLogger
    @OpenTelemetry.grpcTraceOTel
    def maintenance_procedure_operations(self, request, context):
        response = MaintenanceProcedureOperationAppService_maintenanceProcedureOperationsResponse
        try:
            import src.port_adapter.AppDi as AppDi
            maintenanceProcedureOperationAppService: MaintenanceProcedureOperationApplicationService = (
                AppDi.instance.get(MaintenanceProcedureOperationApplicationService)
            )
            return super().models(request=request, context=context, response=response,
                                     appServiceMethod=maintenanceProcedureOperationAppService.maintenanceProcedureOperations,
                                     responseAttribute='maintenance_procedure_operations'
                                     )

        except MaintenanceProcedureOperationDoesNotExistException:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("No maintenanceProcedureOperations found")
            return response()
        except UnAuthorizedException:
            context.set_code(grpc.StatusCode.PERMISSION_DENIED)
            context.set_details("Un Authorized")
            return response()

    @debugLogger
    @OpenTelemetry.grpcTraceOTel
    def maintenance_procedure_operations_by_maintenance_procedure_id(self, request, context):
        response = MaintenanceProcedureOperationAppService_maintenanceProcedureOperationsByMaintenanceProcedureIdResponse
        try:
            import src.port_adapter.AppDi as AppDi
            maintenanceProcedureOperationAppService: MaintenanceProcedureOperationApplicationService = (
                AppDi.instance.get(MaintenanceProcedureOperationApplicationService)
            )
            return super().models(request=request, context=context, response=response,
                                  appServiceMethod=maintenanceProcedureOperationAppService.maintenanceProcedureOperationsByMaintenanceProcedureId,
                                  responseAttribute='maintenance_procedure_operations',
                                  appServiceParams={'maintenanceProcedureId': request.maintenance_procedure_id}
                                  )

        except MaintenanceProcedureOperationDoesNotExistException:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("No maintenanceProcedureOperations found")
            return response()
        except UnAuthorizedException:
            context.set_code(grpc.StatusCode.PERMISSION_DENIED)
            context.set_details("Un Authorized")
            return response()

    @debugLogger
    @OpenTelemetry.grpcTraceOTel
    def maintenance_procedure_operation_by_id(self, request, context):
        response = MaintenanceProcedureOperationAppService_maintenanceProcedureOperationByIdResponse
        try:
            import src.port_adapter.AppDi as AppDi
            maintenanceProcedureOperationAppService: MaintenanceProcedureOperationApplicationService = (
                AppDi.instance.get(MaintenanceProcedureOperationApplicationService)
            )
            return super().oneModel(request=request, context=context,
                                     response=response,
                                     appServiceMethod=maintenanceProcedureOperationAppService.maintenanceProcedureOperationById,
                                     responseAttribute='maintenance_procedure_operation',
                                     appServiceParams={'id': request.id}
                                     )
        except MaintenanceProcedureOperationDoesNotExistException:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("daily check procedure does not exist")
            return response()
        except UnAuthorizedException:
            context.set_code(grpc.StatusCode.PERMISSION_DENIED)
            context.set_details("Un Authorized")
            return response()

    def _addObjectToGrpcResponse(self, obj: MaintenanceProcedureOperation, grpcResponseObject):
        kwargs = {
            "id": obj.id(),
            "name": obj.name() if obj.name() is not None else '',
            "description": obj.description() if obj.description() is not None else '',
            "type": obj.type() if obj.type() is not None else '',
            "maintenance_procedure_id": obj.maintenanceProcedureId() if obj.maintenanceProcedureId() is not None else '',
        }
        for k, v in kwargs.items():
            setattr(grpcResponseObject, k, v)
