---

global:
  setting:
    tab_size: 4 # 4 spaces
  path:
    application: 'src/application'
    domain_model: 'src/domain_model'
    exception: 'src/domain_model/resource/exception'
    port_adapter: 'src/port_adapter'
    repository: 'src/port_adapter/repository'
    db_model: 'src/port_adapter/repository/db_model'
    messaging_listener: 'src/port_adapter/messaging/listener'
    grpc_api_listener: 'src/port_adapter/api/grpc/listener'
    proto_buffer: 'src/resource/proto'
    test: 'test'
    app_di: 'src/port_adapter'

domain_model:
  - model: 
      skip: [ model, domain_service, app_service, domain_repository, repository_impl, db_repository, listener, test, app_di ]
      path: project/standard_equipment
      file_overwrite: True
      name: standard_equipment
      field:
        - name: name
          type: str
          default: None
          proto:
            type: string
        - name: standard_equipment_category_id
          type: str
          default: None
          proto:
            type: string
        - name: standard_equipment_category_group_id
          type: str
          default: None
          proto:
            type: string   
        - name: manufacturer_id
          type: str
          default: None
          proto:
            type: string
        - name: equipment_model_id
          type: str
          default: None
          proto:
            type: string     

  - model: 
      skip: [ model, domain_service, app_service, domain_repository, repository_impl, db_repository, listener, test, app_di ]
      path: project/standard_equipment/standard_category
      file_overwrite: True
      name: standard_equipment_category
      field:
        - name: name
          type: str
          default: None
          proto:
            type: string

  - model: 
      skip: [ model, domain_service, app_service, domain_repository, repository_impl, db_repository, listener, test, app_di ]
      path: project/standard_equipment/standard_category/standard_group
      file_overwrite: True
      name: standard_equipment_category_group
      field:
        - name: name
          type: str
          default: None
          proto:
            type: string
        - name: standard_equipment_category_id
          type: str
          default: None
          proto:
            type: string 

  - model: 
      skip: [ model, domain_service, app_service, domain_repository, repository_impl, db_repository, listener, test, app_di ]
      path: standard_maintenance_procedure
      file_overwrite: True
      name: standard_maintenance_procedure
      field:
        - name: name
          type: str
          default: None
          proto:
            type: string
        - name: type
          type: str
          default: None
          proto:
            type: string 
        - name: sub_type
          type: str
          default: None
          proto:
            type: string
        - name: frequency
          type: str
          default: None
          proto:
            type: string 
        - name: start_date
          type: int
          default: None
          proto:
            type: int32
        - name: organization_id
          type: str
          default: None
          proto:
            type: string 
        - name: standard_equipment_category_group_id
          type: str
          default: None
          proto:
            type: string 




        

#     skip: [all, model, domain_service, app_service, domain_repository, repository_impl, db_repository, listener, proto, grcp, test, app_di]
#     file_overwrite: True
#        #Overwrite the file even if it was modified manually, otherwise, the file will not be overwritten


segment:
  ---
# This can introduce in this example maintenanceProceduresByEquipmentId method in the app/domain service, repo, grpc, proto, ...etc
#  - name: maintenance_procedure
#    foreign:
#        model: *equipment_model


