@startuml "system"
!include puml/c4_container.puml
!include puml/c4_component.puml

skinparam wrapWidth 200
skinparam maxMessageSize 200

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


Container_Boundary(redis, "Redis System") {
	Component(api__redis, "Api Caching & Response", "tcp", "Has response, caching results")
}
Container_Boundary(api, "Api Microservice") {
	Component(api__permission_context_py__update, "Update Permission context", "json/https", "Update permission context")
	Component(api__role_py__update, "Update Role", "json/https", "Update role")
	Component(api__permission_py__delete, "Delete Permission", "json/https", "Delete permission")
	Component(api__ou_py__update, "Update Ou", "json/https", "Update ou")
	Component(api__permission_py__getPermissions, "Get permissions", "json/https", "get all permissions")
	Component(api__permission_py__update, "Update Permission", "json/https", "Update permission")
	Component(api__user_group_py__getUserGroups, "Get user groups", "json/https", "get all user groups")
	Component(api__auth_py__logout, "logout", "json/https", "logout a user")
	Component(api__user_py__create, "Create User", "json/https", "Create user")
	Component(api__ou_py__create, "Create Ou", "json/https", "Create ou")
	Component(api__user_py__resetUserPassword, "Reset User Password", "json/https", "Reset user password")
	Component(api__ou_py__getOu, "Get one ou", "json/https", "get a ou by id")
	Component(api__permission_context_py__delete, "Delete Permission context", "json/https", "Delete permission context")
	Component(api__permission_context_py__getPermissionContext, "Get one permission context", "json/https", "get a permission contextby id")
	Component(api__user_py__getUsers, "Get users", "json/https", "get all users")
	Component(api__project_py__delete, "Delete Project", "json/https", "Delete project")
	Component(api__project_py__getProjects, "Get projects", "json/https", "get all projects")
	Component(api__realm_py__create, "Create Realm", "json/https", "Create realm")
	Component(api__project_py__getProject, "Get one project", "json/https", "get a project by id")
	Component(api__role_py__delete, "Delete Role", "json/https", "Delete role")
	Component(api__ou_py__delete, "Delete Ou", "json/https", "Delete ou")
	Component(api__role_py__getRole, "Get one role", "json/https", "get a role by id")
	Component(api__permission_py__create, "Create Permission", "json/https", "Create permission")
	Component(api__permission_py__getPermission, "Get one permission", "json/https", "get a permission by id")
	Component(api__user_group_py__getUserGroup, "Get one user group", "json/https", "get a user group by id")
	Component(api__project_py__create, "Create Project", "json/https", "Create project")
	Component(api__realm_py__getRealms, "Get realms", "json/https", "get all realms")
	Component(api__user_group_py__delete, "Delete UserGroup", "json/https", "Delete user group")
	Component(api__auth_py__authenticate, "Authenticate a user", "json/https", "Authenticate a user")
	Component(api__user_py__delete, "Delete User", "json/https", "Delete user")
	Component(api__user_group_py__create, "Create UserGroup", "json/https", "Create user group")
	Component(api__realm_py__getRealm, "Get one realm", "json/https", "get a realm by id")
	Component(api__realm_py__update, "Update Realm", "json/https", "Update realm")
	Component(api__ou_py__getOus, "Get ous", "json/https", "get all ous")
	Component(api__permission_context_py__create, "Create Permission context", "json/https", "Create permission context")
	Component(api__realm_py__delete, "Delete Realm", "json/https", "Delete realm")
	Component(api__role_py__create, "Create Role", "json/https", "Create role")
	Component(api__permission_context_py__getPermissionContexts, "Get permission contexts", "json/https", "get all permission contexts")
	Component(api__user_py__getUser, "Get one user", "json/https", "get a user by id")
	Component(api__role_py__getRoles, "Get roles", "json/https", "get all roles")
	Component(api__user_group_py__update, "Update UserGroup", "json/https", "Update user group")
	Component(api__user_py__setUserPassword, "Set User Password", "json/https", "Set user password")
}
Container_Boundary(identity, "Identity Microservice") {
	ComponentQueue(identity__domainmodel_event__RoleDeleted, "Role Deleted", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteUserOneTimePasswordHandler, "Delete user one time password", "identity command consumer", "Delete user one time password")
	ComponentQueue(identity__messaging_api_command_handler__UpdatePermissionContextHandler, "Update permission context", "api command consumer", "Update command")
	ComponentQueue(identity__domainmodel_event__OuCreated, "Ou Created", "event", "message")
	ComponentQueue(identity__messaging_api_command_handler__DeleteUserGroupHandler, "Delete user group", "api command consumer", "Delete command")
	Component(identity__grpc__RealmAppServiceListener__realmById, "Get realm by id", "grpc listener", "Get a realm by id")
	ComponentQueue(identity__messaging_api_command_handler__UpdateRoleHandler, "Update role", "api command consumer", "Update command")
	ComponentQueue(identity__messaging_identity_command_handler__DeletePermissionContextHandler, "Delete permission context", "identity command consumer", "Delete command")
	ComponentQueue(identity__messaging_identity_command_handler__GenerateUserOneTimePasswordHandler, "Generate one time password", "identity command consumer", "Generate user one time password")
	ComponentQueue(identity__domainmodel_event__ProjectDeleted, "Project Deleted", "event", "message")
	ComponentQueue(identity__domainmodel_event__UserGroupUpdated, "User Group Updated", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__UpdateUserHandler, "Update user", "identity command consumer", "Update user")
	ComponentQueue(identity__messaging_identity_command_handler__CreateUserGroupHandler, "Create user group", "identity command consumer", "Create user group")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteRealmHandler, "Delete realm", "identity command consumer", "Delete realm")
	ComponentQueue(identity__messaging_api_command_handler__CreateRoleHandler, "Create role", "api command consumer", "Create command")
	ComponentQueue(identity__messaging_identity_command_handler__UpdateRealmHandler, "Update realm", "identity command consumer", "Update realm")
	ComponentQueue(identity__messaging_identity_command_handler__DeletePermissionHandler, "Delete permission", "identity command consumer", "Delete command")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteProjectHandler, "Delete project", "identity command consumer", "Delete project")
	ComponentQueue(identity__domainmodel_event__UserUpdated, "User Updated", "event", "message")
	ComponentQueue(identity__domainmodel_event__RoleToUserAssignmentRevoked, "Role to User Assignment Revoked", "event", "message")
	ComponentQueue(identity__messaging_project_event_handler__UserUpdatedHandler, "User updated by the project", "project event consumer", "User updated by project")
	ComponentQueue(identity__messaging_api_command_handler__UpdateProjectHandler, "Update project", "api command consumer", "Update command")
	ComponentQueue(identity__messaging_api_command_handler__UpdateUserGroupHandler, "Update user group", "api command consumer", "Update command")
	ComponentQueue(identity__domainmodel_event__UserToRealmAssignmentRevoked, "User to Realm Assignment Revoked", "event", "message")
	Component(identity__grpc__PermissionContextAppServiceListener__permissionContextById, "Get permission context by id", "grpc listener", "Get a permission context by id")
	Component(identity__grpc__CityAppServiceListener__cityById, "Get city by id", "grpc listener", "Get a city by id")
	ComponentQueue(identity__messaging_api_command_handler__DeleteRealmHandler, "Delete realm", "api command consumer", "Delete command")
	Component(identity__grpc__CountryAppServiceListener__cityByCountryId, "Get city by country id", "grpc listener", "Get a city by country id")
	Component(identity__grpc__UserAppServiceListener__userById, "Get user by id", "grpc listener", "Get a user by id")
	ComponentQueue(identity__messaging_identity_command_handler__UpdatePermissionHandler, "Update permission", "identity command consumer", "Update command")
	ComponentQueue(identity__domainmodel_event__OuUpdated, "Ou Updated", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__SendEmailOneTimeUserPasswordHandler, "Send email one time password", "identity command consumer", "Send one time password by email")
	Component(identity__grpc__CityAppServiceListener__cities, "Get cities", "grpc listener", "Get all cities")
	Component(identity__grpc__OuAppServiceListener__ouById, "Get ou by id", "grpc listener", "Get a ou by id")
	ComponentQueue(identity__messaging_api_command_handler__DeletePermissionContextHandler, "Delete permission context", "api command consumer", "Delete command")
	ComponentQueue(identity__messaging_api_command_handler__CreateRealmHandler, "Create realm", "api command consumer", "Create command")
	ComponentQueue(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, "User with one time password logged in", "identity event consumer", "User one time password logged in")
	ComponentQueue(identity__messaging_identity_command_handler__UpdateOuHandler, "Update ou", "identity command consumer", "Update command")
	ComponentQueue(identity__messaging_identity_command_handler__CreatePermissionContextHandler, "Create permission context", "identity command consumer", "Create command")
	ComponentQueue(identity__domainmodel_event__RoleCreated, "Role Created", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__CreateRealmHandler, "Create realm", "identity command consumer", "Create realm")
	ComponentQueue(identity__messaging_api_command_handler__CreatePermissionHandler, "Create permission", "api command consumer", "Create command")
	ComponentQueue(identity__domainmodel_event__OuDeleted, "Ou Deleted", "event", "message")
	Component(identity__grpc__UserGroupAppServiceListener__userGroups, "Get user groups", "grpc listener", "Get all user groups")
	ComponentQueue(identity__domainmodel_event__RealmUpdated, "Realm Updated", "event", "message")
	ComponentQueue(identity__messaging_api_command_handler__DeletePermissionHandler, "Delete permission", "api command consumer", "Delete command")
	ComponentQueue(identity__domainmodel_event__UserGroupDeleted, "User Group Deleted", "event", "message")
	ComponentQueue(identity__messaging_project_event_handler__UserCreatedHandler, "User created by the project", "project event consumer", "User created by project")
	ComponentQueue(identity__domainmodel_event__PermissionCreated, "Permission Created", "event", "message")
	ComponentQueue(identity__domainmodel_event__ProjectUpdated, "Project Updated", "event", "message")
	ComponentQueue(identity__domainmodel_event__PermissionContextUpdated, "Permission Context Updated", "event", "message")
	Component(identity__grpc__PermissionContextAppServiceListener__permissionContexts, "Get permission contexts", "grpc listener", "Get all permission contexts")
	ComponentQueue(identity__domainmodel_event__PermissionDeleted, "Permission Deleted", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteOuHandler, "Delete ou", "identity command consumer", "Delete command")
	Component(identity__grpc__PermissionAppServiceListener__permissionById, "Get permission by id", "grpc listener", "Get a permission by id")
	ComponentQueue(identity__messaging_api_command_handler__UpdateRealmHandler, "Update realm", "api command consumer", "Update command")
	ComponentQueue(identity__domainmodel_event__PermissionUpdated, "Permission Updated", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__CreatePermissionHandler, "Create permission", "identity command consumer", "Create command")
	ComponentQueue(identity__messaging_api_command_handler__CreateOuHandler, "Create ou", "api command consumer", "Create command")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteRoleHandler, "Delete role", "identity command consumer", "Delete role")
	ComponentQueue(identity__messaging_identity_command_handler__UpdateProjectHandler, "Update project", "identity command consumer", "Update project")
	ComponentQueue(identity__messaging_identity_command_handler__CreateUserHandler, "Create user", "identity command consumer", "Create user")
	ComponentQueue(identity__messaging_identity_command_handler__CreateOuHandler, "Create ou", "identity command consumer", "Create command")
	ComponentQueue(identity__domainmodel_event__UserToRealmAssigned, "User to Realm Assigned", "event", "message")
	ComponentQueue(identity__domainmodel_event__RoleToUserAssigned, "Role to User Assigned", "event", "message")
	Component(identity__grpc__OuAppServiceListener__ous, "Get ous", "grpc listener", "Get all ous")
	ComponentQueue(identity__messaging_api_command_handler__CreatePermissionContextHandler, "Create permission context", "api command consumer", "Create command")
	ComponentQueue(identity__messaging_identity_command_handler__CreateRoleHandler, "Create role", "identity command consumer", "Create role")
	ComponentQueue(identity__messaging_identity_command_handler__UpdateUserGroupHandler, "Update user group", "identity command consumer", "Update user group")
	ComponentQueue(identity__domainmodel_event__UserGroupCreated, "User Group Created", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__SetUserPasswordHandler, "Set user password", "identity command consumer", "Set user password")
	ComponentQueue(identity__domainmodel_event__UserOneTimePasswordGenerated, "User One Time Password Generated", "event", "message")
	ComponentQueue(identity__messaging_identity_command_handler__CreateProjectHandler, "Create project", "identity command consumer", "Create project")
	ComponentQueue(identity__domainmodel_event__PermissionContextCreated, "Permission Context Created", "event", "message")
	ComponentQueue(identity__messaging_identity_event_handler__UserOneTimePasswordGeneratedHandler, "User one time password generated", "identity event consumer", "User one time password generated")
	Component(identity__grpc__UserAppServiceListener__users, "Get users", "grpc listener", "Get all users")
	ComponentQueue(identity__messaging_api_command_handler__DeleteUserHandler, "Delete user", "api command consumer", "Delete command")
	ComponentQueue(identity__domainmodel_event__ProjectCreated, "Project Created", "event", "message")
	ComponentQueue(identity__messaging_api_command_handler__UpdatePermissionHandler, "Update permission", "api command consumer", "Update command")
	Component(identity__grpc__RealmAppServiceListener__realms, "Get realms", "grpc listener", "Get all realms")
	ComponentQueue(identity__domainmodel_event__UserPasswordSet, "User Password Set", "event", "message")
	Component(identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc listener", "Get all projects")
	Component(identity__grpc__AuthAppServiceListener__authenticateUserByEmailAndPassword, "Auth user by email and password", "grpc listener", "Authenticate a user")
	Component(identity__grpc__ProjectAppServiceListener__projectById, "Get project by id", "grpc listener", "Get a project by id")
	Component(identity__grpc__CountryAppServiceListener__countryById, "Get country by id", "grpc listener", "Get a country by id")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteUserHandler, "Delete user", "identity command consumer", "Delete user")
	Component(identity__grpc__UserGroupAppServiceListener__userGroupById, "Get user group by id", "grpc listener", "Get a user group by id")
	ComponentQueue(identity__domainmodel_event__PermissionContextDeleted, "Permission Context Deleted", "event", "message")
	Component(identity__grpc__AuthAppServiceListener__logout, "Logout user", "grpc listener", "Logout a user")
	ComponentQueue(identity__messaging_api_command_handler__CreateUserHandler, "Create user", "api command consumer", "Create command")
	Component(identity__grpc__RoleAppServiceListener__roleById, "Get role by id", "grpc listener", "Get a role by id")
	Component(identity__grpc__CountryAppServiceListener__countries, "Get countries", "grpc listener", "Get all countries")
	ComponentQueue(identity__messaging_identity_command_handler__UpdateRoleHandler, "Update role", "identity command consumer", "Update role")
	ComponentQueue(identity__messaging_api_command_handler__UpdateUserHandler, "Update user", "api command consumer", "Update command")
	ComponentQueue(identity__domainmodel_event__UserCreated, "User Created", "event", "message")
	ComponentQueue(identity__messaging_api_command_handler__SetUserPasswordHandler, "Set user password", "api command consumer", "Set user password command")
	ComponentQueue(identity__domainmodel_event__RealmCreated, "Realm Created", "event", "message")
	ComponentQueue(identity__messaging_api_command_handler__DeleteRoleHandler, "Delete role", "api command consumer", "Delete command")
	ComponentQueue(identity__messaging_api_command_handler__DeleteProjectHandler, "Delete project", "api command consumer", "Delete command")
	ComponentQueue(identity__messaging_identity_command_handler__UpdatePermissionContextHandler, "Update permission context", "identity command consumer", "Update command")
	ComponentQueue(identity__messaging_api_command_handler__ResetUserPasswordHandler, "Reset user password", "api command consumer", "Reset user password command")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteUserGroupHandler, "Delete user group", "identity command consumer", "Delete user group")
	ComponentQueue(identity__domainmodel_event__UserDeleted, "User Deleted", "event", "message")
	ComponentQueue(identity__messaging_api_command_handler__CreateUserGroupHandler, "Create user group", "api command consumer", "Create command")
	ComponentQueue(identity__domainmodel_event__RealmDeleted, "Realm Deleted", "event", "message")
	Component(identity__grpc__PermissionAppServiceListener__permissions, "Get permission", "grpc listener", "Get all permissions")
	Component(identity__grpc__CountryAppServiceListener__citiesByCountryId, "Get cities by country id", "grpc listener", "Get cities by country id")
	ComponentQueue(identity__messaging_api_command_handler__DeleteOuHandler, "Delete ou", "api command consumer", "Delete command")
	ComponentQueue(identity__messaging_api_command_handler__CreateProjectHandler, "Create project", "api command consumer", "Create command")
	ComponentQueue(identity__messaging_api_command_handler__UpdateOuHandler, "Update ou", "api command consumer", "Update command")
	ComponentQueue(identity__domainmodel_event__UserWithOneTimePasswordLoggedIn, "User With One Time Password Logged In", "event", "message")
	Component(identity__grpc__RoleAppServiceListener__roles, "Get roles", "grpc listener", "Get all roles")
	ComponentQueue(identity__domainmodel_event__RoleUpdated, "Role Updated", "event", "message")
}
Container_Boundary(project, "Project Microservice") {
	ComponentQueue(project__domainmodel_event__ProjectUpdated, "Project Updated", "event", "message")
	ComponentQueue(project__domainmodel_event__RoleCreated, "Role Created", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__AssignUserToOrganizationHandler, "Assign User to Organization", "project command consumer", "Assign User to Organization")
	ComponentQueue(project__domainmodel_event__OrganizationDeleted, "Organization Deleted", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, "Revoke User to Organization Assignment", "project command consumer", "Revoke User to Organization Assignment")
	ComponentQueue(project__domainmodel_event__RoleToUserAssigned, "Role to User Assigned", "event", "message")
	ComponentQueue(project__domainmodel_event__ProjectStateChanged, "Project State Changed", "event", "message")
	ComponentQueue(project__domainmodel_event__OrganizationUpdated, "Organization Updated", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__UpdateOrganizationHandler, "Update Organization", "project command consumer", "Update Organization")
	ComponentQueue(project__messaging_identity_event_handler__UserCreatedHandler, "User Created", "identity event consumer", "User created")
	ComponentQueue(project__domainmodel_event__UserToOrganizationAssignmentRevoked, "User to Organization Assignment Revoked", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, "Revoke Role to User Assignment", "project command consumer", "Revoke Role to User Assignment")
	Component(identity__grpc__UserAppServiceListener__userByEmail, "Get a user by email", "grpc listener", "Get a user by email")
	ComponentQueue(project__domainmodel_event__UserCreated, "User Created", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__DeleteOrganizationHandler, "Delete Organization", "project command consumer", "Delete Organization")
	ComponentQueue(project__messaging_identity_event_handler__RoleToUserAssignedHandler, "Role to User Assigned", "identity event consumer", "Role to user assigned")
	ComponentQueue(project__messaging_project_command_handler__CreateRoleHandler, "Create Role", "project command consumer", "Create Role")
	ComponentQueue(project__messaging_project_command_handler__CreateUserHandler, "Create User", "project command consumer", "Create User")
	ComponentQueue(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, "Role to User Assignment Revoked", "identity event consumer", "Role to user assignment revoked")
	Component(identity__grpc__UserLookupAppServiceListener__userLookups, "Get a user lookups", "grpc listener", "Get user lookups")
	ComponentQueue(project__messaging_identity_event_handler__UserToRealmAssignedHandler, "User to Realm Assigned", "identity event consumer", "User to Realm Assigned")
	ComponentQueue(project__messaging_project_command_handler__AssignRoleToUserHandler, "Assign Role to User", "project command consumer", "Assign Role to User")
	ComponentQueue(project__domainmodel_event__UserToOrganizationAssigned, "User to Organization Assigned", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__ProjectCreatedHandler, "Project Created", "identity event consumer", "Project created")
	Component(identity__grpc__ProjectAppServiceListener__projectByName, "Get project by name", "grpc listener", "Get a project by name")
	Component(identity__grpc__UserLookupAppServiceListener__userLookupByUserEmail, "Get a user lookup by email", "grpc listener", "Get a user lookup by email")
	Component(identity__grpc__OrganizationAppServiceListener__organizationById, "Get organization by id", "grpc listener", "Get a organization by id")
	ComponentQueue(project__messaging_project_command_handler__UpdateUserHandler, "Update User", "project command consumer", "Update User")
	ComponentQueue(project__domainmodel_event__ProjectCreated, "Project Created", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__RealmCreatedHandler, "Realm Created", "identity event consumer", "Realm created")
	ComponentQueue(project__domainmodel_event__UserUpdated, "User Updated", "event", "message")
	ComponentQueue(project__domainmodel_event__UserDeleted, "User Deleted", "event", "message")
	Component(identity__grpc__OrganizationAppServiceListener__organizations, "Get organizations", "grpc listener", "Get all organizations")
	ComponentQueue(project__domainmodel_event__ProjectDeleted, "Project Created", "event", "message")
	Component(identity__grpc__UserAppServiceListener__users, "Get all users", "grpc listener", "Get users")
	ComponentQueue(project__messaging_identity_event_handler__UserDeletedHandler, "User Deleted", "identity event consumer", "User deleted")
	Component(identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc listener", "Get all projects")
	Component(identity__grpc__UserAppServiceListener__userById, "Get a user by id", "grpc listener", "Get a user by id")
	Component(identity__grpc__ProjectAppServiceListener__projectById, "Get project by id", "grpc listener", "Get a project by id")
	Component(identity__grpc__UserLookupAppServiceListener__userLookupByUserId, "Get a user lookup by id", "grpc listener", "Get a user lookup by id")
	ComponentQueue(project__messaging_identity_event_handler__RoleCreatedHandler, "Role Created", "identity event consumer", "Role created")
	ComponentQueue(project__messaging_project_command_handler__DeleteUserHandler, "Delete User", "project command consumer", "Delete User")
	ComponentQueue(project__messaging_project_command_handler__CreateOrganizationHandler, "Create Organization", "project command consumer", "Create Organization")
	ComponentQueue(project__domainmodel_event__RoleDeleted, "Role Deleted", "event", "message")
	ComponentQueue(project__domainmodel_event__OrganizationCreated, "Organization Created", "event", "message")
	ComponentQueue(project__domainmodel_event__RoleToUserAssignmentRevoked, "Role to User Assignment Revoked", "event", "message")
	ComponentQueue(project__domainmodel_event__RoleUpdated, "Role Updated", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__UserUpdatedHandler, "User Updated", "identity event consumer", "User updated")
	ComponentQueue(project__messaging_project_command_handler__CreateProjectHandler, "Create Project", "project command consumer", "Create Project")
	ComponentQueue(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, "User to Realm Assignement Revoked", "identity event consumer", "User to Realm Assignment Revoked")
	ComponentQueue(project__messaging_identity_event_handler__ProjectDeletedHandler, "Project Deleted", "identity event consumer", "Project deleted")
	ComponentQueue(project__messaging_project_command_handler__DeleteProjectHandler, "Delete Project", "project command consumer", "Delete Project")
}
Rel(api__permission_py__getPermissions, identity__grpc__PermissionAppServiceListener__permissions, "Get permissions", "grpc call")
Rel(api__auth_py__logout, identity__grpc__AuthAppServiceListener__logout, "Logout user by token", "grpc call")
Rel(api__permission_py__create, identity__messaging_api_command_handler__CreatePermissionHandler, "Create permission", "message")
Rel(identity__domainmodel_event__ProjectDeleted, project__messaging_identity_event_handler__ProjectDeletedHandler, "Project Deleted", "message")
Rel(identity__messaging_api_command_handler__UpdateRealmHandler, identity__messaging_identity_command_handler__UpdateRealmHandler, "Update realm", "message")
Rel(identity__messaging_identity_command_handler__UpdateUserHandler, identity__domainmodel_event__UserUpdated, "User Updated", "message")
Rel(identity__domainmodel_event__ProjectCreated, project__messaging_identity_event_handler__ProjectCreatedHandler, "Project Created", "message")
Rel(identity__messaging_identity_command_handler__UpdatePermissionContextHandler, identity__domainmodel_event__PermissionContextUpdated, "PermissionContext Updated", "message")
Rel(identity__domainmodel_event__RoleToUserAssignmentRevoked, project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, "Role to User Assignment Revoked", "message")
Rel(identity__messaging_identity_command_handler__UpdateRoleHandler, identity__domainmodel_event__RoleUpdated, "Role Updated", "message")
Rel(api__permission_context_py__getPermissionContexts, identity__grpc__PermissionContextAppServiceListener__permissionContexts, "Get permission contexts", "grpc call")
Rel(identity__messaging_api_command_handler__DeleteUserHandler, identity__messaging_identity_command_handler__DeleteUserHandler, "Delete user", "message")
Rel(project__messaging_project_command_handler__CreateRoleHandler, project__domainmodel_event__RoleCreated, "Role Created", "message")
Rel(api__user_py__setUserPassword, identity__messaging_api_command_handler__SetUserPasswordHandler, "Set user password", "message")
Rel(api__realm_py__getRealm, identity__grpc__RealmAppServiceListener__realmById, "Get a realm by id", "grpc call")
Rel(identity__messaging_identity_command_handler__UpdateProjectHandler, identity__domainmodel_event__ProjectUpdated, "Project Updated", "message")
Rel(project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, project__domainmodel_event__RoleToUserAssignmentRevoked, "Role to User Assignment Revoked", "message")
Rel(api__role_py__delete, identity__messaging_api_command_handler__DeleteRoleHandler, "Delete role", "message")
Rel(identity__messaging_project_event_handler__UserCreatedHandler, identity__messaging_identity_command_handler__GenerateUserOneTimePasswordHandler, "Generate password", "message")
Rel(api__user_group_py__getUserGroup, identity__grpc__UserGroupAppServiceListener__userGroupById, "Get a user group by id", "grpc call")
Rel(identity__messaging_api_command_handler__UpdateProjectHandler, identity__messaging_identity_command_handler__UpdateProjectHandler, "Update project", "message")
Rel(api__realm_py__update, identity__messaging_api_command_handler__UpdateRealmHandler, "Update realm", "message")
Rel(project__messaging_identity_event_handler__UserCreatedHandler, project__messaging_project_command_handler__CreateUserHandler, "Create User", "message")
Rel(identity__messaging_identity_command_handler__CreateUserGroupHandler, identity__domainmodel_event__UserGroupCreated, "UserGroup Created", "message")
Rel(identity__messaging_api_command_handler__UpdateUserHandler, identity__messaging_identity_command_handler__UpdateUserHandler, "Update user", "message")
Rel(api__ou_py__getOu, identity__grpc__OuAppServiceListener__ouById, "Get an ou by id", "grpc call")
Rel(identity__messaging_api_command_handler__DeleteProjectHandler, identity__messaging_identity_command_handler__DeleteProjectHandler, "Delete project", "message")
Rel(api__role_py__getRole, identity__grpc__RoleAppServiceListener__roleById, "Get a role by id", "grpc call")
Rel(api__permission_context_py__getPermissionContext, identity__grpc__PermissionContextAppServiceListener__permissionContextById, "Get a permission contextby id", "grpc call")
Rel(api__permission_py__update, identity__messaging_api_command_handler__UpdatePermissionHandler, "Update permission", "message")
Rel(api__auth_py__authenticate, identity__grpc__AuthAppServiceListener__authenticateUserByEmailAndPassword, "Auth user & get token", "grpc call")
Rel(api__realm_py__delete, identity__messaging_api_command_handler__DeleteRealmHandler, "Delete realm", "message")
Rel(identity__messaging_identity_command_handler__CreatePermissionContextHandler, identity__domainmodel_event__PermissionContextCreated, "PermissionContext Created", "message")
Rel(api__role_py__create, identity__messaging_api_command_handler__CreateRoleHandler, "Create role", "message")
Rel(identity__messaging_api_command_handler__DeleteRoleHandler, identity__messaging_identity_command_handler__DeleteRoleHandler, "Delete role", "message")
Rel(identity__messaging_api_command_handler__CreateUserHandler, identity__messaging_identity_command_handler__CreateUserHandler, "Create user", "message")
Rel(identity__messaging_identity_command_handler__DeleteUserGroupHandler, identity__domainmodel_event__UserGroupDeleted, "UserGroup Deleted", "message")
Rel(identity__messaging_identity_command_handler__CreateRoleHandler, identity__domainmodel_event__RoleCreated, "Role Created", "message")
Rel(identity__messaging_identity_command_handler__UpdateRealmHandler, identity__domainmodel_event__RealmUpdated, "Realm Updated", "message")
Rel(project__messaging_project_command_handler__DeleteUserHandler, project__domainmodel_event__UserDeleted, "User Deleted", "message")
Rel(api__project_py__getProjects, identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc call")
Rel(identity__messaging_identity_command_handler__UpdatePermissionHandler, identity__domainmodel_event__PermissionUpdated, "Permission Updated", "message")
Rel(identity__domainmodel_event__UserCreated, project__messaging_identity_event_handler__UserCreatedHandler, "User Created", "message")
Rel(identity__messaging_api_command_handler__DeleteUserGroupHandler, identity__messaging_identity_command_handler__DeleteUserGroupHandler, "Delete user group", "message")
Rel(project__messaging_identity_event_handler__RoleToUserAssignedHandler, project__messaging_project_command_handler__AssignRoleToUserHandler, "Assign Role to User", "message")
Rel(project__messaging_project_command_handler__DeleteOrganizationHandler, project__domainmodel_event__OrganizationDeleted, "Organization Deleted", "message")
Rel(api__ou_py__create, identity__messaging_api_command_handler__CreateOuHandler, "Create ou", "message")
Rel(api__user_group_py__update, identity__messaging_api_command_handler__UpdateUserGroupHandler, "Update user group", "message")
Rel(api__role_py__getRoles, identity__grpc__RoleAppServiceListener__roles, "Get roles", "grpc call")
Rel(project__messaging_identity_event_handler__RoleCreatedHandler, project__messaging_project_command_handler__CreateRoleHandler, "Create Role", "message")
Rel(project__messaging_identity_event_handler__ProjectDeletedHandler, project__messaging_project_command_handler__DeleteProjectHandler, "Delete Project", "message")
Rel(project__messaging_project_command_handler__DeleteProjectHandler, project__domainmodel_event__ProjectDeleted, "Project Deleted", "message")
Rel(project__messaging_identity_event_handler__UserDeletedHandler, project__messaging_project_command_handler__DeleteUserHandler, "Delete user", "message")
Rel(api__ou_py__update, identity__messaging_api_command_handler__UpdateOuHandler, "Update ou", "message")
Rel(identity__messaging_api_command_handler__CreateRealmHandler, identity__messaging_identity_command_handler__CreateRealmHandler, "Create realm", "message")
Rel(identity__messaging_identity_command_handler__CreateRealmHandler, identity__domainmodel_event__RealmCreated, "Realm Created", "message")
Rel(identity__messaging_identity_command_handler__UpdateUserGroupHandler, identity__domainmodel_event__UserGroupUpdated, "UserGroup Updated", "message")
Rel(identity__messaging_api_command_handler__DeletePermissionHandler, identity__messaging_identity_command_handler__DeletePermissionHandler, "Delete permission", "message")
Rel(api__permission_py__delete, identity__messaging_api_command_handler__DeletePermissionHandler, "Delete permission", "message")
Rel(project__messaging_project_command_handler__UpdateUserHandler, project__domainmodel_event__UserUpdated, "User Updated", "message")
Rel(identity__domainmodel_event__RoleCreated, project__messaging_identity_event_handler__RoleCreatedHandler, "Role Created", "message")
Rel(api__ou_py__delete, identity__messaging_api_command_handler__DeleteOuHandler, "Delete ou", "message")
Rel(api__user_group_py__getUserGroups, identity__grpc__UserGroupAppServiceListener__userGroups, "Get user groups", "grpc call")
Rel(identity__messaging_api_command_handler__UpdateUserGroupHandler, identity__messaging_identity_command_handler__UpdateUserGroupHandler, "Update user group", "message")
Rel(api__user_group_py__delete, identity__messaging_api_command_handler__DeleteUserGroupHandler, "Delete user group", "message")
Rel(project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, project__domainmodel_event__UserToOrganizationAssignmentRevoked, "User to Organization Assignment Revoked", "message")
Rel(api__permission_context_py__update, identity__messaging_api_command_handler__UpdatePermissionContextHandler, "Update permission context", "message")
Rel(identity__messaging_identity_command_handler__DeletePermissionContextHandler, identity__domainmodel_event__PermissionContextDeleted, "PermissionContext Deleted", "message")
Rel(identity__domainmodel_event__UserUpdated, project__messaging_identity_event_handler__UserUpdatedHandler, "User Updated", "message")
Rel(identity__messaging_identity_command_handler__DeletePermissionHandler, identity__domainmodel_event__PermissionDeleted, "Permission Deleted", "message")
Rel(project__messaging_project_command_handler__AssignUserToOrganizationHandler, project__domainmodel_event__UserToOrganizationAssigned, "User to Organization Assgined", "message")
Rel(identity__messaging_identity_command_handler__DeleteRoleHandler, identity__domainmodel_event__RoleDeleted, "Role Deleted", "message")
Rel(api__role_py__update, identity__messaging_api_command_handler__UpdateRoleHandler, "Update role", "message")
Rel(project__messaging_project_command_handler__CreateUserHandler, project__domainmodel_event__UserCreated, "User Created", "message")
Rel(api__user_py__getUsers, identity__grpc__UserAppServiceListener__users, "Get users", "grpc call")
Rel(api__user_py__getUser, identity__grpc__UserAppServiceListener__userById, "Get a user by id", "grpc call")
Rel(api__realm_py__create, identity__messaging_api_command_handler__CreateRealmHandler, "Create realm", "message")
Rel(identity__messaging_project_event_handler__UserUpdatedHandler, identity__messaging_identity_command_handler__UpdateUserHandler, "Update user", "message")
Rel(api__permission_context_py__create, identity__messaging_api_command_handler__CreatePermissionContextHandler, "Create permission context", "message")
Rel(identity__messaging_identity_command_handler__DeleteProjectHandler, identity__domainmodel_event__ProjectDeleted, "Project Deleted", "message")
Rel(api__project_py__create, identity__messaging_api_command_handler__CreateProjectHandler, "Create project", "message")
Rel(api__user_py__create, identity__messaging_api_command_handler__CreateUserHandler, "Create user", "message")
Rel(project__messaging_identity_event_handler__UserUpdatedHandler, project__messaging_project_command_handler__UpdateUserHandler, "Update User", "message")
Rel(api__realm_py__getRealms, identity__grpc__RealmAppServiceListener__realms, "Get realms", "grpc call")
Rel(identity__messaging_identity_command_handler__DeleteOuHandler, identity__domainmodel_event__OuDeleted, "Ou Deleted", "message")
Rel(identity__messaging_api_command_handler__DeleteRealmHandler, identity__messaging_identity_command_handler__DeleteRealmHandler, "Delete realm", "message")
Rel(identity__messaging_api_command_handler__UpdatePermissionHandler, identity__messaging_identity_command_handler__UpdatePermissionHandler, "Update permission", "message")
Rel(api__project_py__getProject, identity__grpc__ProjectAppServiceListener__projectById, "Get a project by id", "grpc call")
Rel(identity__messaging_identity_command_handler__CreateProjectHandler, identity__domainmodel_event__ProjectCreated, "Project Created", "message")
Rel(api__permission_py__getPermission, identity__grpc__PermissionAppServiceListener__permissionById, "Get a permission by id", "grpc call")
Rel(identity__messaging_api_command_handler__UpdateRoleHandler, identity__messaging_identity_command_handler__UpdateRoleHandler, "Update role", "message")
Rel(api__project_py__delete, identity__messaging_api_command_handler__DeleteProjectHandler, "Delete project", "message")
Rel(project__messaging_identity_event_handler__UserToRealmAssignedHandler, project__messaging_project_command_handler__AssignUserToOrganizationHandler, "Assign User to Organization", "message")
Rel(identity__messaging_identity_command_handler__UpdateOuHandler, identity__domainmodel_event__OuUpdated, "Ou Updated", "message")
Rel(identity__messaging_api_command_handler__DeletePermissionContextHandler, identity__messaging_identity_command_handler__DeletePermissionContextHandler, "Delete permission context", "message")
Rel(identity__messaging_identity_command_handler__CreateUserHandler, identity__domainmodel_event__UserCreated, "User Created", "message")
Rel(identity__messaging_identity_command_handler__CreatePermissionHandler, identity__domainmodel_event__PermissionCreated, "Permission Created", "message")
Rel(api__user_py__delete, identity__messaging_api_command_handler__DeleteUserHandler, "Delete user", "message")
Rel(identity__messaging_api_command_handler__CreateRoleHandler, identity__messaging_identity_command_handler__CreateRoleHandler, "Create role", "message")
Rel(identity__messaging_identity_command_handler__DeleteUserHandler, identity__domainmodel_event__UserDeleted, "User Deleted", "message")
Rel(identity__messaging_identity_command_handler__DeleteRealmHandler, identity__domainmodel_event__RealmDeleted, "Realm Deleted", "message")
Rel(identity__messaging_api_command_handler__SetUserPasswordHandler, identity__messaging_identity_command_handler__SetUserPasswordHandler, "Set user password", "message")
Rel(project__messaging_project_command_handler__AssignRoleToUserHandler, project__domainmodel_event__RoleToUserAssigned, "Role to User Assgined", "message")
Rel(identity__domainmodel_event__UserDeleted, project__messaging_identity_event_handler__UserDeletedHandler, "User Deleted", "message")
Rel(identity__messaging_api_command_handler__UpdatePermissionContextHandler, identity__messaging_identity_command_handler__UpdatePermissionContextHandler, "Update permission context", "message")
Rel(project__messaging_identity_event_handler__ProjectCreatedHandler, project__messaging_project_command_handler__CreateProjectHandler, "Create Project", "message")
Rel(project__messaging_identity_event_handler__RealmCreatedHandler, project__messaging_project_command_handler__CreateOrganizationHandler, "Create Organization", "message")
Rel(project__messaging_project_command_handler__CreateProjectHandler, project__domainmodel_event__ProjectCreated, "Project Created", "message")
Rel(identity__messaging_identity_command_handler__CreateOuHandler, identity__domainmodel_event__OuCreated, "Ou Created", "message")
Rel(identity__messaging_api_command_handler__DeleteOuHandler, identity__messaging_identity_command_handler__DeleteOuHandler, "Delete ou", "message")
Rel(identity__messaging_identity_command_handler__GenerateUserOneTimePasswordHandler, identity__domainmodel_event__UserOneTimePasswordGenerated, "User one time password generated", "message")
Rel(api__ou_py__getOus, identity__grpc__OuAppServiceListener__ous, "Get ous", "grpc call")
Rel(identity__messaging_api_command_handler__CreateUserGroupHandler, identity__messaging_identity_command_handler__CreateOuHandler, "Create user group", "message")
Rel(identity__domainmodel_event__RoleToUserAssigned, project__messaging_identity_event_handler__RoleToUserAssignedHandler, "Role to User Assigned", "message")
Rel(identity__messaging_api_command_handler__CreateProjectHandler, identity__messaging_identity_command_handler__CreateProjectHandler, "Create project", "message")
Rel(identity__messaging_api_command_handler__CreatePermissionHandler, identity__messaging_identity_command_handler__CreatePermissionHandler, "Create permission", "message")
Rel(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, identity__messaging_identity_command_handler__DeleteUserOneTimePasswordHandler, "Send email one time user password", "message")
Rel(identity__messaging_api_command_handler__CreatePermissionContextHandler, identity__messaging_identity_command_handler__CreatePermissionContextHandler, "Create permission context", "message")
Rel(identity__domainmodel_event__UserToRealmAssigned, project__messaging_identity_event_handler__UserToRealmAssignedHandler, "User to Realm Assigned", "message")
Rel(identity__messaging_identity_event_handler__UserOneTimePasswordGeneratedHandler, identity__messaging_identity_command_handler__SendEmailOneTimeUserPasswordHandler, "Send email one time user password", "message")
Rel(identity__domainmodel_event__RealmCreated, project__messaging_identity_event_handler__RealmCreatedHandler, "Realm Created", "message")
Rel(identity__messaging_api_command_handler__ResetUserPasswordHandler, identity__messaging_identity_command_handler__GenerateUserOneTimePasswordHandler, "Reset user password", "message")
Rel(api__user_group_py__create, identity__messaging_api_command_handler__CreateUserGroupHandler, "Create user group", "message")
Rel(identity__messaging_api_command_handler__CreateOuHandler, identity__messaging_identity_command_handler__CreateOuHandler, "Create ou", "message")
Rel(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, "Revoke Role to User Assignment", "message")
Rel(identity__messaging_api_command_handler__UpdateOuHandler, identity__messaging_identity_command_handler__UpdateOuHandler, "Update ou", "message")
Rel(api__user_py__resetUserPassword, identity__messaging_api_command_handler__ResetUserPasswordHandler, "Reset user password", "message")
Rel(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, "Revoke User to Organization Assignment", "message")
Rel(api__permission_context_py__delete, identity__messaging_api_command_handler__DeletePermissionContextHandler, "Delete permission context", "message")
Rel(identity__domainmodel_event__UserToRealmAssignmentRevoked, project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, "User to Realm Assignment Revoked", "message")
Rel(project__messaging_project_command_handler__UpdateOrganizationHandler, project__domainmodel_event__OrganizationUpdated, "Organization Updated", "message")
Rel(project__messaging_project_command_handler__CreateOrganizationHandler, project__domainmodel_event__OrganizationCreated, "Organization Created", "message")
Rel(api, redis, "Get/Create api response & caching data")

@enduml
