"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""



from elasticsearch_dsl import InnerDoc, Keyword, Float, Nested

from src.port_adapter.repository.es_model.lookup.equipment.Unit import Unit


class MaintenanceProcedureOperationParameter(InnerDoc):
    id = Keyword()
    name = Keyword()
    min_value = Float()
    max_value = Float()
    unit = Nested(Unit)
