"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""


from elasticsearch_dsl import InnerDoc, Keyword

from src.port_adapter.repository.es_model.model.EsModelAttributeData import (
    EsModelAttributeData,
)
from src.resource.logging.logger import logger


class Subcontractor(InnerDoc):
    id = Keyword()
    company_name = Keyword()

    @classmethod
    def attributeDataBySnakeCaseAttributeName(
        cls, instance: "Subcontractor" = None, snakeCaseAttributeName: str = None
    ) -> EsModelAttributeData:
        # Remove any dots for nested objects, e.g. country.id should become country
        periodIndex = snakeCaseAttributeName.rfind(".")
        if periodIndex != -1:
            snakeCaseAttributeName = snakeCaseAttributeName[:periodIndex]
        mapping = {
            "id": EsModelAttributeData(
                attributeModelName="id",
                attributeRepoName="id",
                attributeRepoValue=getattr(instance, "id", None),
            ),
            "company_name": EsModelAttributeData(
                attributeModelName="company_name",
                attributeRepoName="company_name",
                attributeRepoValue=getattr(instance, "company_name", None),
            ),
        }

        return (
            mapping[snakeCaseAttributeName]
            if snakeCaseAttributeName in mapping
            else None
        )
