# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import equipment_category_app_service_pb2 as equipment__category__app__service__pb2


class EquipmentCategoryAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.equipmentCategoryById = channel.unary_unary(
                '/cafm.project.equipment_category.EquipmentCategoryAppService/equipmentCategoryById',
                request_serializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryByIdRequest.SerializeToString,
                response_deserializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryByIdResponse.FromString,
                )
        self.equipmentCategorys = channel.unary_unary(
                '/cafm.project.equipment_category.EquipmentCategoryAppService/equipmentCategorys',
                request_serializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategorysRequest.SerializeToString,
                response_deserializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategorysResponse.FromString,
                )
        self.equipmentCategoryGroupsByCategoryId = channel.unary_unary(
                '/cafm.project.equipment_category.EquipmentCategoryAppService/equipmentCategoryGroupsByCategoryId',
                request_serializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryGroupsByCategoryIdRequest.SerializeToString,
                response_deserializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryGroupsByCategoryIdResponse.FromString,
                )


class EquipmentCategoryAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def equipmentCategoryById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def equipmentCategorys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def equipmentCategoryGroupsByCategoryId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EquipmentCategoryAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'equipmentCategoryById': grpc.unary_unary_rpc_method_handler(
                    servicer.equipmentCategoryById,
                    request_deserializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryByIdRequest.FromString,
                    response_serializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryByIdResponse.SerializeToString,
            ),
            'equipmentCategorys': grpc.unary_unary_rpc_method_handler(
                    servicer.equipmentCategorys,
                    request_deserializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategorysRequest.FromString,
                    response_serializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategorysResponse.SerializeToString,
            ),
            'equipmentCategoryGroupsByCategoryId': grpc.unary_unary_rpc_method_handler(
                    servicer.equipmentCategoryGroupsByCategoryId,
                    request_deserializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryGroupsByCategoryIdRequest.FromString,
                    response_serializer=equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryGroupsByCategoryIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.project.equipment_category.EquipmentCategoryAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EquipmentCategoryAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def equipmentCategoryById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.project.equipment_category.EquipmentCategoryAppService/equipmentCategoryById',
            equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryByIdRequest.SerializeToString,
            equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def equipmentCategorys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.project.equipment_category.EquipmentCategoryAppService/equipmentCategorys',
            equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategorysRequest.SerializeToString,
            equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategorysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def equipmentCategoryGroupsByCategoryId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.project.equipment_category.EquipmentCategoryAppService/equipmentCategoryGroupsByCategoryId',
            equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryGroupsByCategoryIdRequest.SerializeToString,
            equipment__category__app__service__pb2.EquipmentCategoryAppService_equipmentCategoryGroupsByCategoryIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
