"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from sqlalchemy.sql.expression import text

from src.application.lifecycle.ApplicationServiceLifeCycle import ApplicationServiceLifeCycle
from src.domain_model.resource.exception.SubcontractorCategoryDoesNotExistException import (
    SubcontractorCategoryDoesNotExistException,
)
from src.domain_model.subcontractor.category.SubcontractorCategory import SubcontractorCategory
from src.domain_model.subcontractor.category.SubcontractorCategoryRepository import SubcontractorCategoryRepository
from src.domain_model.token.TokenData import TokenData
from src.port_adapter.repository.db_model.SubcontractorCategory import SubcontractorCategory as DbSubcontractorCategory
from src.resource.logging.decorator import debugLogger


class SubcontractorCategoryRepositoryImpl(SubcontractorCategoryRepository):
    @debugLogger
    def save(self, obj: SubcontractorCategory, tokenData: TokenData = None):
        dbSession = ApplicationServiceLifeCycle.dbContext()
        dbObject = dbSession.query(DbSubcontractorCategory).filter_by(id=obj.id()).first()
        if dbObject is not None:
            self.updateSubcontractorCategory(obj=obj, dbObject=dbObject, tokenData=tokenData)
        else:
            self.createSubcontractorCategory(obj=obj, tokenData=tokenData)

    @debugLogger
    def bulkSave(self, objList: List[SubcontractorCategory], tokenData: TokenData = None):
        dbSession = ApplicationServiceLifeCycle.dbContext()
        for obj in objList:
            dbObject = dbSession.query(DbSubcontractorCategory).filter_by(id=obj.id()).first()
            if dbObject is not None:
                dbObject = self._updateDbObjectByObj(dbObject=dbObject, obj=obj)
            else:
                dbObject = self._createDbObjectByObj(obj=obj)
            dbSession.add(dbObject)


    @debugLogger
    def bulkDelete(self, objList: List[SubcontractorCategory], tokenData: TokenData = None) -> None:
        dbSession = ApplicationServiceLifeCycle.dbContext()
        for obj in objList:
            dbObject = dbSession.query(DbSubcontractorCategory).filter_by(id=obj.id()).first()
            if dbObject is not None:
                dbSession.delete(dbObject)


    @debugLogger
    def createSubcontractorCategory(self, obj: SubcontractorCategory, tokenData: TokenData = None):
        dbSession = ApplicationServiceLifeCycle.dbContext()
        dbObject = self._createDbObjectByObj(obj=obj)
        dbSession.add(dbObject)


    @debugLogger
    def deleteSubcontractorCategory(self, obj: SubcontractorCategory, tokenData: TokenData = None) -> None:
        dbSession = ApplicationServiceLifeCycle.dbContext()
        dbObject = dbSession.query(DbSubcontractorCategory).filter_by(id=obj.id()).first()
        if dbObject is not None:
            dbSession.delete(dbObject)
    

    @debugLogger
    def updateSubcontractorCategory(
        self, obj: SubcontractorCategory, dbObject: DbSubcontractorCategory = None, tokenData: TokenData = None
    ) -> None:
        dbSession = ApplicationServiceLifeCycle.dbContext()
        if dbObject is None:
            raise SubcontractorCategoryDoesNotExistException(f"id = {obj.id()}")
        dbSession.add(self._updateDbObjectByObj(dbObject=dbObject, obj=obj))
        

    @debugLogger
    def subcontractorCategoryById(self, id: str) -> SubcontractorCategory:
        dbSession = ApplicationServiceLifeCycle.dbContext()
        dbObject = dbSession.query(DbSubcontractorCategory).filter_by(id=id).first()
        if dbObject is None:
            raise SubcontractorCategoryDoesNotExistException(f"id = {id}")
        return SubcontractorCategory.createFrom(id=dbObject.id, name=dbObject.name)

    @debugLogger
    def subcontractorCategories(
        self, resultFrom: int = 0, resultSize: int = 100, order: List[dict] = None, tokenData: TokenData = None
    ) -> dict:
        dbSession = ApplicationServiceLifeCycle.dbContext()
        sortData = ""
        if order is not None:
            for item in order:
                sortData = f'{sortData}, {item["orderBy"]} {item["direction"]}'
            sortData = sortData[2:]
        items = (
            dbSession.query(DbSubcontractorCategory)
            .order_by(text(sortData))
            .limit(resultSize)
            .offset(resultFrom)
            .all()
        )
        itemsCount = dbSession.query(DbSubcontractorCategory).count()
        if items is None:
            return {"items": [], "totalItemCount": 0}
        return {
            "items": [SubcontractorCategory.createFrom(id=x.id, name=x.name) for x in items],
            "totalItemCount": itemsCount,
        }

    def _updateDbObjectByObj(self, dbObject: DbSubcontractorCategory, obj: SubcontractorCategory):
        dbObject.name = obj.name() if obj.name() is not None else dbObject.name
        return dbObject

    def _createDbObjectByObj(self, obj: SubcontractorCategory):
        return DbSubcontractorCategory(id=obj.id(), name=obj.name())
