"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""
from typing import List
from src.domain_model.project.unit.Unit import Unit
from src.domain_model.project.unit.UnitRepository import UnitRepository
from src.domain_model.resource.exception.UnitAlreadyExistException import (
    UnitAlreadyExistException,
)
from src.domain_model.resource.exception.UnitDoesNotExistException import (
    UnitDoesNotExistException,
)
from src.domain_model.token.TokenData import TokenData
from src.resource.logging.decorator import debugLogger


class UnitService:
    def __init__(self, repository: UnitRepository):
        self._repo = repository

    @debugLogger
    def createUnit(
        self, obj: Unit, objectOnly: bool = False, tokenData: TokenData = None
    ):
        if objectOnly:
            return (
                Unit.createFromObject(obj=obj, generateNewId=True)
                if obj.id() == ""
                else obj
            )
        else:
            obj = Unit.createFromObject(obj=obj, publishEvent=True)
            self._repo.save(obj=obj)
            return obj

    @debugLogger
    def deleteUnit(self, obj: Unit, tokenData: TokenData = None):
        obj.publishDelete()
        self._repo.deleteUnit(obj=obj)

    @debugLogger
    def updateUnit(self, oldObject: Unit, newObject: Unit, tokenData: TokenData = None):
        newObject.publishUpdate(oldObject)
        self._repo.save(obj=newObject)

    @debugLogger
    def units(
        self,
        tokenData: TokenData = None,
        resultFrom: int = 0,
        resultSize: int = 100,
        order: List[dict] = None,
    ):
        return self._repo.units(
            tokenData=tokenData,
            resultFrom=resultFrom,
            resultSize=resultSize,
            order=order,
        )
