"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""


from src.port_adapter.messaging.listener.common.handler.lookup.equipment.UpdateManufacturerHandler import \
    UpdateManufacturerHandler as Handler

class UpdateManufacturerHandler(Handler):
    pass
