# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from identity import auth_app_service_pb2 as identity_dot_auth__app__service__pb2


class AuthAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.authenticate_user_by_email_and_password = channel.unary_unary(
                '/cafm.identity.auth.AuthAppService/authenticate_user_by_email_and_password',
                request_serializer=identity_dot_auth__app__service__pb2.AuthAppService_authenticateUserByEmailAndPasswordRequest.SerializeToString,
                response_deserializer=identity_dot_auth__app__service__pb2.AuthAppService_authenticateUserByEmailAndPasswordResponse.FromString,
                )
        self.is_authenticated = channel.unary_unary(
                '/cafm.identity.auth.AuthAppService/is_authenticated',
                request_serializer=identity_dot_auth__app__service__pb2.AuthAppService_isAuthenticatedRequest.SerializeToString,
                response_deserializer=identity_dot_auth__app__service__pb2.AuthAppService_isAuthenticatedResponse.FromString,
                )
        self.logout = channel.unary_unary(
                '/cafm.identity.auth.AuthAppService/logout',
                request_serializer=identity_dot_auth__app__service__pb2.AuthAppService_logoutRequest.SerializeToString,
                response_deserializer=identity_dot_auth__app__service__pb2.AuthAppService_logoutResponse.FromString,
                )


class AuthAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def authenticate_user_by_email_and_password(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_authenticated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'authenticate_user_by_email_and_password': grpc.unary_unary_rpc_method_handler(
                    servicer.authenticate_user_by_email_and_password,
                    request_deserializer=identity_dot_auth__app__service__pb2.AuthAppService_authenticateUserByEmailAndPasswordRequest.FromString,
                    response_serializer=identity_dot_auth__app__service__pb2.AuthAppService_authenticateUserByEmailAndPasswordResponse.SerializeToString,
            ),
            'is_authenticated': grpc.unary_unary_rpc_method_handler(
                    servicer.is_authenticated,
                    request_deserializer=identity_dot_auth__app__service__pb2.AuthAppService_isAuthenticatedRequest.FromString,
                    response_serializer=identity_dot_auth__app__service__pb2.AuthAppService_isAuthenticatedResponse.SerializeToString,
            ),
            'logout': grpc.unary_unary_rpc_method_handler(
                    servicer.logout,
                    request_deserializer=identity_dot_auth__app__service__pb2.AuthAppService_logoutRequest.FromString,
                    response_serializer=identity_dot_auth__app__service__pb2.AuthAppService_logoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.auth.AuthAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def authenticate_user_by_email_and_password(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.auth.AuthAppService/authenticate_user_by_email_and_password',
            identity_dot_auth__app__service__pb2.AuthAppService_authenticateUserByEmailAndPasswordRequest.SerializeToString,
            identity_dot_auth__app__service__pb2.AuthAppService_authenticateUserByEmailAndPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_authenticated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.auth.AuthAppService/is_authenticated',
            identity_dot_auth__app__service__pb2.AuthAppService_isAuthenticatedRequest.SerializeToString,
            identity_dot_auth__app__service__pb2.AuthAppService_isAuthenticatedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.auth.AuthAppService/logout',
            identity_dot_auth__app__service__pb2.AuthAppService_logoutRequest.SerializeToString,
            identity_dot_auth__app__service__pb2.AuthAppService_logoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
