# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/hashed_key.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity/hashed_key.proto',
  package='cafm.identity.authz',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19identity/hashed_key.proto\x12\x13\x63\x61\x66m.identity.authz\"+\n\tHashedKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\thash_code\x18\x02 \x01(\tb\x06proto3'
)




_HASHEDKEY = _descriptor.Descriptor(
  name='HashedKey',
  full_name='cafm.identity.authz.HashedKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cafm.identity.authz.HashedKey.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash_code', full_name='cafm.identity.authz.HashedKey.hash_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['HashedKey'] = _HASHEDKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HashedKey = _reflection.GeneratedProtocolMessageType('HashedKey', (_message.Message,), {
  'DESCRIPTOR' : _HASHEDKEY,
  '__module__' : 'identity.hashed_key_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.authz.HashedKey)
  })
_sym_db.RegisterMessage(HashedKey)


# @@protoc_insertion_point(module_scope)
