# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/realm_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from identity import realm_pb2 as identity_dot_realm__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity/realm_app_service.proto',
  package='cafm.identity.realm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n identity/realm_app_service.proto\x12\x13\x63\x61\x66m.identity.realm\x1a\x14identity/realm.proto\x1a\x0border.proto\"2\n\"RealmAppService_realmByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"P\n#RealmAppService_realmByNameResponse\x12)\n\x05realm\x18\x01 \x01(\x0b\x32\x1a.cafm.identity.realm.Realm\".\n RealmAppService_realmByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"N\n!RealmAppService_realmByIdResponse\x12)\n\x05realm\x18\x01 \x01(\x0b\x32\x1a.cafm.identity.realm.Realm\"s\n\x1dRealmAppService_realmsRequest\x12\x13\n\x0bresult_from\x18\x01 \x01(\x05\x12\x13\n\x0bresult_size\x18\x02 \x01(\x05\x12(\n\x06orders\x18\x03 \x03(\x0b\x32\x18.cafm.common.order.Order\"f\n\x1eRealmAppService_realmsResponse\x12*\n\x06realms\x18\x01 \x03(\x0b\x32\x1a.cafm.identity.realm.Realm\x12\x18\n\x10total_item_count\x18\x02 \x01(\x05\"\x1e\n\x1cRealmAppService_newIdRequest\"+\n\x1dRealmAppService_newIdResponse\x12\n\n\x02id\x18\x01 \x01(\t2\x80\x04\n\x0fRealmAppService\x12\x84\x01\n\rrealm_by_name\x12\x37.cafm.identity.realm.RealmAppService_realmByNameRequest\x1a\x38.cafm.identity.realm.RealmAppService_realmByNameResponse\"\x00\x12~\n\x0brealm_by_id\x12\x35.cafm.identity.realm.RealmAppService_realmByIdRequest\x1a\x36.cafm.identity.realm.RealmAppService_realmByIdResponse\"\x00\x12s\n\x06realms\x12\x32.cafm.identity.realm.RealmAppService_realmsRequest\x1a\x33.cafm.identity.realm.RealmAppService_realmsResponse\"\x00\x12q\n\x06new_id\x12\x31.cafm.identity.realm.RealmAppService_newIdRequest\x1a\x32.cafm.identity.realm.RealmAppService_newIdResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[identity_dot_realm__pb2.DESCRIPTOR,order__pb2.DESCRIPTOR,])




_REALMAPPSERVICE_REALMBYNAMEREQUEST = _descriptor.Descriptor(
  name='RealmAppService_realmByNameRequest',
  full_name='cafm.identity.realm.RealmAppService_realmByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cafm.identity.realm.RealmAppService_realmByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=142,
)


_REALMAPPSERVICE_REALMBYNAMERESPONSE = _descriptor.Descriptor(
  name='RealmAppService_realmByNameResponse',
  full_name='cafm.identity.realm.RealmAppService_realmByNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='realm', full_name='cafm.identity.realm.RealmAppService_realmByNameResponse.realm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=224,
)


_REALMAPPSERVICE_REALMBYIDREQUEST = _descriptor.Descriptor(
  name='RealmAppService_realmByIdRequest',
  full_name='cafm.identity.realm.RealmAppService_realmByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cafm.identity.realm.RealmAppService_realmByIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=272,
)


_REALMAPPSERVICE_REALMBYIDRESPONSE = _descriptor.Descriptor(
  name='RealmAppService_realmByIdResponse',
  full_name='cafm.identity.realm.RealmAppService_realmByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='realm', full_name='cafm.identity.realm.RealmAppService_realmByIdResponse.realm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=352,
)


_REALMAPPSERVICE_REALMSREQUEST = _descriptor.Descriptor(
  name='RealmAppService_realmsRequest',
  full_name='cafm.identity.realm.RealmAppService_realmsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_from', full_name='cafm.identity.realm.RealmAppService_realmsRequest.result_from', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_size', full_name='cafm.identity.realm.RealmAppService_realmsRequest.result_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orders', full_name='cafm.identity.realm.RealmAppService_realmsRequest.orders', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=469,
)


_REALMAPPSERVICE_REALMSRESPONSE = _descriptor.Descriptor(
  name='RealmAppService_realmsResponse',
  full_name='cafm.identity.realm.RealmAppService_realmsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='realms', full_name='cafm.identity.realm.RealmAppService_realmsResponse.realms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_item_count', full_name='cafm.identity.realm.RealmAppService_realmsResponse.total_item_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=573,
)


_REALMAPPSERVICE_NEWIDREQUEST = _descriptor.Descriptor(
  name='RealmAppService_newIdRequest',
  full_name='cafm.identity.realm.RealmAppService_newIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=605,
)


_REALMAPPSERVICE_NEWIDRESPONSE = _descriptor.Descriptor(
  name='RealmAppService_newIdResponse',
  full_name='cafm.identity.realm.RealmAppService_newIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cafm.identity.realm.RealmAppService_newIdResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=650,
)

_REALMAPPSERVICE_REALMBYNAMERESPONSE.fields_by_name['realm'].message_type = identity_dot_realm__pb2._REALM
_REALMAPPSERVICE_REALMBYIDRESPONSE.fields_by_name['realm'].message_type = identity_dot_realm__pb2._REALM
_REALMAPPSERVICE_REALMSREQUEST.fields_by_name['orders'].message_type = order__pb2._ORDER
_REALMAPPSERVICE_REALMSRESPONSE.fields_by_name['realms'].message_type = identity_dot_realm__pb2._REALM
DESCRIPTOR.message_types_by_name['RealmAppService_realmByNameRequest'] = _REALMAPPSERVICE_REALMBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['RealmAppService_realmByNameResponse'] = _REALMAPPSERVICE_REALMBYNAMERESPONSE
DESCRIPTOR.message_types_by_name['RealmAppService_realmByIdRequest'] = _REALMAPPSERVICE_REALMBYIDREQUEST
DESCRIPTOR.message_types_by_name['RealmAppService_realmByIdResponse'] = _REALMAPPSERVICE_REALMBYIDRESPONSE
DESCRIPTOR.message_types_by_name['RealmAppService_realmsRequest'] = _REALMAPPSERVICE_REALMSREQUEST
DESCRIPTOR.message_types_by_name['RealmAppService_realmsResponse'] = _REALMAPPSERVICE_REALMSRESPONSE
DESCRIPTOR.message_types_by_name['RealmAppService_newIdRequest'] = _REALMAPPSERVICE_NEWIDREQUEST
DESCRIPTOR.message_types_by_name['RealmAppService_newIdResponse'] = _REALMAPPSERVICE_NEWIDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RealmAppService_realmByNameRequest = _reflection.GeneratedProtocolMessageType('RealmAppService_realmByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMBYNAMEREQUEST,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_realmByNameRequest)
  })
_sym_db.RegisterMessage(RealmAppService_realmByNameRequest)

RealmAppService_realmByNameResponse = _reflection.GeneratedProtocolMessageType('RealmAppService_realmByNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMBYNAMERESPONSE,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_realmByNameResponse)
  })
_sym_db.RegisterMessage(RealmAppService_realmByNameResponse)

RealmAppService_realmByIdRequest = _reflection.GeneratedProtocolMessageType('RealmAppService_realmByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMBYIDREQUEST,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_realmByIdRequest)
  })
_sym_db.RegisterMessage(RealmAppService_realmByIdRequest)

RealmAppService_realmByIdResponse = _reflection.GeneratedProtocolMessageType('RealmAppService_realmByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMBYIDRESPONSE,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_realmByIdResponse)
  })
_sym_db.RegisterMessage(RealmAppService_realmByIdResponse)

RealmAppService_realmsRequest = _reflection.GeneratedProtocolMessageType('RealmAppService_realmsRequest', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMSREQUEST,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_realmsRequest)
  })
_sym_db.RegisterMessage(RealmAppService_realmsRequest)

RealmAppService_realmsResponse = _reflection.GeneratedProtocolMessageType('RealmAppService_realmsResponse', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMSRESPONSE,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_realmsResponse)
  })
_sym_db.RegisterMessage(RealmAppService_realmsResponse)

RealmAppService_newIdRequest = _reflection.GeneratedProtocolMessageType('RealmAppService_newIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_NEWIDREQUEST,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_newIdRequest)
  })
_sym_db.RegisterMessage(RealmAppService_newIdRequest)

RealmAppService_newIdResponse = _reflection.GeneratedProtocolMessageType('RealmAppService_newIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_NEWIDRESPONSE,
  '__module__' : 'identity.realm_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.realm.RealmAppService_newIdResponse)
  })
_sym_db.RegisterMessage(RealmAppService_newIdResponse)



_REALMAPPSERVICE = _descriptor.ServiceDescriptor(
  name='RealmAppService',
  full_name='cafm.identity.realm.RealmAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=653,
  serialized_end=1165,
  methods=[
  _descriptor.MethodDescriptor(
    name='realm_by_name',
    full_name='cafm.identity.realm.RealmAppService.realm_by_name',
    index=0,
    containing_service=None,
    input_type=_REALMAPPSERVICE_REALMBYNAMEREQUEST,
    output_type=_REALMAPPSERVICE_REALMBYNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='realm_by_id',
    full_name='cafm.identity.realm.RealmAppService.realm_by_id',
    index=1,
    containing_service=None,
    input_type=_REALMAPPSERVICE_REALMBYIDREQUEST,
    output_type=_REALMAPPSERVICE_REALMBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='realms',
    full_name='cafm.identity.realm.RealmAppService.realms',
    index=2,
    containing_service=None,
    input_type=_REALMAPPSERVICE_REALMSREQUEST,
    output_type=_REALMAPPSERVICE_REALMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='new_id',
    full_name='cafm.identity.realm.RealmAppService.new_id',
    index=3,
    containing_service=None,
    input_type=_REALMAPPSERVICE_NEWIDREQUEST,
    output_type=_REALMAPPSERVICE_NEWIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REALMAPPSERVICE)

DESCRIPTOR.services_by_name['RealmAppService'] = _REALMAPPSERVICE

# @@protoc_insertion_point(module_scope)
