# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from identity import user_app_service_pb2 as identity_dot_user__app__service__pb2


class UserAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.user_by_email_and_password = channel.unary_unary(
                '/cafm.identity.user.UserAppService/user_by_email_and_password',
                request_serializer=identity_dot_user__app__service__pb2.UserAppService_userByEmailAndPasswordRequest.SerializeToString,
                response_deserializer=identity_dot_user__app__service__pb2.UserAppService_userByEmailAndPasswordResponse.FromString,
                )
        self.user_by_id = channel.unary_unary(
                '/cafm.identity.user.UserAppService/user_by_id',
                request_serializer=identity_dot_user__app__service__pb2.UserAppService_userByIdRequest.SerializeToString,
                response_deserializer=identity_dot_user__app__service__pb2.UserAppService_userByIdResponse.FromString,
                )
        self.users = channel.unary_unary(
                '/cafm.identity.user.UserAppService/users',
                request_serializer=identity_dot_user__app__service__pb2.UserAppService_usersRequest.SerializeToString,
                response_deserializer=identity_dot_user__app__service__pb2.UserAppService_usersResponse.FromString,
                )
        self.new_id = channel.unary_unary(
                '/cafm.identity.user.UserAppService/new_id',
                request_serializer=identity_dot_user__app__service__pb2.UserAppService_newIdRequest.SerializeToString,
                response_deserializer=identity_dot_user__app__service__pb2.UserAppService_newIdResponse.FromString,
                )
        self.has_user_password_set = channel.unary_unary(
                '/cafm.identity.user.UserAppService/has_user_password_set',
                request_serializer=identity_dot_user__app__service__pb2.UserAppService_hasUserPasswordSetRequest.SerializeToString,
                response_deserializer=identity_dot_user__app__service__pb2.UserAppService_hasUserPasswordSetResponse.FromString,
                )


class UserAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def user_by_email_and_password(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def users(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def new_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def has_user_password_set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'user_by_email_and_password': grpc.unary_unary_rpc_method_handler(
                    servicer.user_by_email_and_password,
                    request_deserializer=identity_dot_user__app__service__pb2.UserAppService_userByEmailAndPasswordRequest.FromString,
                    response_serializer=identity_dot_user__app__service__pb2.UserAppService_userByEmailAndPasswordResponse.SerializeToString,
            ),
            'user_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.user_by_id,
                    request_deserializer=identity_dot_user__app__service__pb2.UserAppService_userByIdRequest.FromString,
                    response_serializer=identity_dot_user__app__service__pb2.UserAppService_userByIdResponse.SerializeToString,
            ),
            'users': grpc.unary_unary_rpc_method_handler(
                    servicer.users,
                    request_deserializer=identity_dot_user__app__service__pb2.UserAppService_usersRequest.FromString,
                    response_serializer=identity_dot_user__app__service__pb2.UserAppService_usersResponse.SerializeToString,
            ),
            'new_id': grpc.unary_unary_rpc_method_handler(
                    servicer.new_id,
                    request_deserializer=identity_dot_user__app__service__pb2.UserAppService_newIdRequest.FromString,
                    response_serializer=identity_dot_user__app__service__pb2.UserAppService_newIdResponse.SerializeToString,
            ),
            'has_user_password_set': grpc.unary_unary_rpc_method_handler(
                    servicer.has_user_password_set,
                    request_deserializer=identity_dot_user__app__service__pb2.UserAppService_hasUserPasswordSetRequest.FromString,
                    response_serializer=identity_dot_user__app__service__pb2.UserAppService_hasUserPasswordSetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.user.UserAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def user_by_email_and_password(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.user.UserAppService/user_by_email_and_password',
            identity_dot_user__app__service__pb2.UserAppService_userByEmailAndPasswordRequest.SerializeToString,
            identity_dot_user__app__service__pb2.UserAppService_userByEmailAndPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.user.UserAppService/user_by_id',
            identity_dot_user__app__service__pb2.UserAppService_userByIdRequest.SerializeToString,
            identity_dot_user__app__service__pb2.UserAppService_userByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def users(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.user.UserAppService/users',
            identity_dot_user__app__service__pb2.UserAppService_usersRequest.SerializeToString,
            identity_dot_user__app__service__pb2.UserAppService_usersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def new_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.user.UserAppService/new_id',
            identity_dot_user__app__service__pb2.UserAppService_newIdRequest.SerializeToString,
            identity_dot_user__app__service__pb2.UserAppService_newIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def has_user_password_set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.user.UserAppService/has_user_password_set',
            identity_dot_user__app__service__pb2.UserAppService_hasUserPasswordSetRequest.SerializeToString,
            identity_dot_user__app__service__pb2.UserAppService_hasUserPasswordSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
