"""
The file is generated by scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from src.application.BaseApplicationService import BaseApplicationService
from src.application.model.BaseApplicationServiceBulkData import BaseApplicationServiceBulkData
from src.application.model.BaseApplicationServiceModelData import BaseApplicationServiceModelData
from src.domain_model.project.equipment.category.group.EquipmentCategoryGroupRepository import (
    EquipmentCategoryGroupRepository,
)
from src.domain_model.project.equipment.project_category.EquipmentProjectCategory import (
    EquipmentProjectCategory,
)
from src.domain_model.project.equipment.project_category.EquipmentProjectCategoryRepository import (
    EquipmentProjectCategoryRepository,
)
from src.domain_model.project.equipment.project_category.EquipmentProjectCategoryService import (
    EquipmentProjectCategoryService,
)
from src.domain_model.resource.exception.UpdateEquipmentProjectCategoryFailedException import (
    UpdateEquipmentProjectCategoryFailedException,
)
from src.domain_model.token.TokenService import TokenService
from src.resource.logging.decorator import debugLogger


class EquipmentProjectCategoryApplicationService(BaseApplicationService):
    def __init__(
        self,
        repo: EquipmentProjectCategoryRepository,
        groupRepo: EquipmentCategoryGroupRepository,
        equipmentProjectCategoryService: EquipmentProjectCategoryService,
    ):
        self._repo = repo
        self._groupRepo = groupRepo
        self._equipmentProjectCategoryService = equipmentProjectCategoryService

    @debugLogger
    def newId(self):
        return EquipmentProjectCategory.createFrom(skipValidation=True).id()

    @debugLogger
    def createEquipmentProjectCategory(self, token: str = None, objectOnly: bool = False, **kwargs):
        obj: EquipmentProjectCategory = self._constructObject(**kwargs)
        tokenData = TokenService.tokenDataFromToken(token=token)
        return self._equipmentProjectCategoryService.createEquipmentProjectCategory(
            obj=obj, objectOnly=objectOnly, tokenData=tokenData
        )

    @debugLogger
    def linkEquipmentProjectCategoryGroup(self, id: str, categoryGroupId: str, token: str = None):
        from src.domain_model.project.equipment.project_category.EquipmentProjectCategory import (
            EquipmentProjectCategory,
        )
        from src.domain_model.project.equipment.category.group.EquipmentCategoryGroup import (
            EquipmentCategoryGroup,
        )

        category: EquipmentProjectCategory = self._repo.equipmentProjectCategoryById(id=id)
        group: EquipmentCategoryGroup = self._groupRepo.equipmentCategoryGroupById(id=categoryGroupId)
        _tokenData = TokenService.tokenDataFromToken(token=token)
        self._equipmentProjectCategoryService.linkEquipmentProjectCategoryToGroup(category=category, group=group)

    @debugLogger
    def unLinkEquipmentProjectCategoryGroup(self, id: str, categoryGroupId: str, token: str = None):
        from src.domain_model.project.equipment.project_category.EquipmentProjectCategory import (
            EquipmentProjectCategory,
        )
        from src.domain_model.project.equipment.category.group.EquipmentCategoryGroup import (
            EquipmentCategoryGroup,
        )

        category: EquipmentProjectCategory = self._repo.equipmentProjectCategoryById(id=id)
        group: EquipmentCategoryGroup = self._groupRepo.equipmentCategoryGroupById(id=categoryGroupId)
        _tokenData = TokenService.tokenDataFromToken(token=token)
        self._equipmentProjectCategoryService.unlinkEquipmentProjectCategoryToGroup(category=category, group=group)

    @debugLogger
    def equipmentCategoryGroupsByProjectCategoryId(
        self,
        id: str,
        resultFrom: int = 0,
        resultSize: int = 100,
        order: List[dict] = None,
        token: str = None,
    ) -> dict:
        tokenData = TokenService.tokenDataFromToken(token=token)
        return self._equipmentProjectCategoryService.equipmentCategoryGroupsByProjectCategoryId(
            tokenData=tokenData,
            id=id,
            resultFrom=resultFrom,
            resultSize=resultSize,
            order=order,
        )

    @debugLogger
    def updateEquipmentProjectCategory(
        self,
        token: str = None,
        **kwargs,
    ):
        tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            oldObject: EquipmentProjectCategory = self._repo.equipmentProjectCategoryById(id=kwargs["id"])
            super().callFunction(
                modelData=BaseApplicationServiceModelData(
                    function=self._equipmentProjectCategoryService.updateEquipmentProjectCategory,
                    kwargs={
                        "oldObject": oldObject,
                        "newObject": self._constructObject(_sourceObject=oldObject, **kwargs),
                        "tokenData": tokenData,
                    },
                )
            )

        except Exception as e:
            raise UpdateEquipmentProjectCategoryFailedException(message=str(e))

    @debugLogger
    def deleteEquipmentProjectCategory(self, id: str, token: str = None):
        super().callFunction(
            modelData=BaseApplicationServiceModelData(
                function=self._equipmentProjectCategoryService.deleteEquipmentProjectCategory,
                kwargs={
                    "obj": self._repo.equipmentProjectCategoryById(id=id),
                    "tokenData": TokenService.tokenDataFromToken(token=token),
                },
            )
        )

    @debugLogger
    def bulkCreate(self, objListParams: List[dict], token: str = ""):
        super()._bulkCreate(
            baseBulkData=BaseApplicationServiceBulkData(
                objListParams=objListParams,
                token=token,
                sourceId="equipment_project_category_id",
                domainService=self._equipmentProjectCategoryService,
            )
        )

    @debugLogger
    def bulkDelete(self, objListParams: List[dict], token: str = ""):
        super()._bulkDelete(
            baseBulkData=BaseApplicationServiceBulkData(
                objListParams=objListParams,
                token=token,
                sourceId="equipment_project_category_id",
                domainService=self._equipmentProjectCategoryService,
            )
        )

    @debugLogger
    def bulkUpdate(self, objListParams: List[dict], token: str = ""):
        super()._bulkUpdate(
            baseBulkData=BaseApplicationServiceBulkData(
                objListParams=objListParams,
                token=token,
                sourceId="equipment_project_category_id",
                domainService=self._equipmentProjectCategoryService,
                repositoryCallbackFunction=self._repo.equipmentProjectCategoryById,
            )
        )

    @debugLogger
    def equipmentProjectCategoryById(self, id: str, token: str = None) -> EquipmentProjectCategory:
        TokenService.tokenDataFromToken(token=token)
        return super().callGetterFunction(
            modelData=BaseApplicationServiceModelData(
                getterFunction=self._repo.equipmentProjectCategoryById, kwargs={"id": id}
            )
        )

    @debugLogger
    def equipmentProjectCategories(
        self,
        resultFrom: int = 0,
        resultSize: int = 100,
        order: List[dict] = None,
        token: str = None,
    ) -> dict:
        tokenData = TokenService.tokenDataFromToken(token=token)
        return super().callGetterFunction(
            modelData=BaseApplicationServiceModelData(
                getterFunction=self._equipmentProjectCategoryService.equipmentProjectCategories,
                kwargs={"resultFrom": resultFrom, "resultSize": resultSize, "order": order, "tokenData": tokenData},
            )
        )

    @debugLogger
    def _constructObject(self, *args, **kwargs) -> EquipmentProjectCategory:
        kwargs[BaseApplicationService.DOMAIN_MODEL_CLASS] = EquipmentProjectCategory
        return super()._constructObject(*args, **kwargs)
