"""
The file is generated by scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from src.application.BaseApplicationService import BaseApplicationService
from src.domain_model.manufacturer.ManufacturerRepository import ManufacturerRepository
from src.domain_model.project.equipment.model.EquipmentModelRepository import (
    EquipmentModelRepository,
)
from src.domain_model.project.standard_equipment.StandardEquipment import (
    StandardEquipment,
)
from src.domain_model.project.standard_equipment.StandardEquipmentRepository import (
    StandardEquipmentRepository,
)
from src.domain_model.project.standard_equipment.StandardEquipmentService import (
    StandardEquipmentService,
)
from src.domain_model.project.standard_equipment.standard_category.StandardEquipmentCategoryRepository import (
    StandardEquipmentCategoryRepository,
)
from src.domain_model.project.standard_equipment.standard_category.standard_group.StandardEquipmentCategoryGroupRepository import (
    StandardEquipmentCategoryGroupRepository,
)
from src.domain_model.resource.exception.DomainModelException import DomainModelException
from src.domain_model.resource.exception.ProcessBulkDomainException import ProcessBulkDomainException
from src.domain_model.resource.exception.UpdateStandardEquipmentFailedException import (
    UpdateStandardEquipmentFailedException,
)
from src.domain_model.token.TokenService import TokenService
from src.domain_model.util.DomainModelAttributeValidator import DomainModelAttributeValidator
from src.resource.logging.decorator import debugLogger


class StandardEquipmentApplicationService(BaseApplicationService):
    def __init__(
        self,
        repo: StandardEquipmentRepository,
        standardEquipmentService: StandardEquipmentService,
        standardEquipmentCategoryRepo: StandardEquipmentCategoryRepository,
        standardEquipmentCategoryGroupRepo: StandardEquipmentCategoryGroupRepository,
        manufacturerRepo: ManufacturerRepository,
        equipmentModelRepo: EquipmentModelRepository,
    ):
        self._repo = repo
        self._standardEquipmentService = standardEquipmentService
        self._standardEquipmentCategoryRepo = standardEquipmentCategoryRepo
        self._standardEquipmentCategoryGroupRepo = standardEquipmentCategoryGroupRepo
        self._manufacturerRepo = manufacturerRepo
        self._equipmentModelRepo = equipmentModelRepo

    @debugLogger
    def newId(self):
        return StandardEquipment.createFrom(skipValidation=True).id()

    @debugLogger
    def createStandardEquipment(
        self,
        id: str = None,
        name: str = None,
        standardEquipmentCategoryId: str = None,
        standardEquipmentCategoryGroupId: str = None,
        manufacturerId: str = None,
        equipmentModelId: str = None,
        objectOnly: bool = False,
        token: str = "",
    ):
        obj: StandardEquipment = self._constructObject(
            id=id,
            name=name,
            standardEquipmentCategoryId=standardEquipmentCategoryId,
            standardEquipmentCategoryGroupId=standardEquipmentCategoryGroupId,
            manufacturerId=manufacturerId,
            equipmentModelId=equipmentModelId,
        )
        tokenData = TokenService.tokenDataFromToken(token=token)
        self._standardEquipmentCategoryRepo.standardEquipmentCategoryById(id=standardEquipmentCategoryId)
        self._standardEquipmentCategoryGroupRepo.standardEquipmentCategoryGroupById(id=standardEquipmentCategoryGroupId)
        self._manufacturerRepo.manufacturerById(id=manufacturerId)
        self._equipmentModelRepo.equipmentModelById(id=equipmentModelId)
        return self._standardEquipmentService.createStandardEquipment(
            obj=obj, objectOnly=objectOnly, tokenData=tokenData
        )

    @debugLogger
    def updateStandardEquipment(
        self,
        id: str,
        name: str = None,
        standardEquipmentCategoryId: str = None,
        standardEquipmentCategoryGroupId: str = None,
        manufacturerId: str = None,
        equipmentModelId: str = None,
        token: str = None,
    ):
        tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            oldObject: StandardEquipment = self._repo.standardEquipmentById(id=id)
            obj: StandardEquipment = self._constructObject(
                id=id,
                name=name,
                standardEquipmentCategoryId=standardEquipmentCategoryId,
                standardEquipmentCategoryGroupId=standardEquipmentCategoryGroupId,
                manufacturerId=manufacturerId,
                equipmentModelId=equipmentModelId,
                _sourceObject=oldObject,
            )
            self._standardEquipmentService.updateStandardEquipment(
                oldObject=oldObject, newObject=obj, tokenData=tokenData
            )
        except Exception as e:
            raise UpdateStandardEquipmentFailedException(message=str(e))

    @debugLogger
    def deleteStandardEquipment(self, id: str, token: str = None):
        tokenData = TokenService.tokenDataFromToken(token=token)
        obj = self._repo.standardEquipmentById(id=id)
        self._standardEquipmentService.deleteStandardEquipment(obj=obj, tokenData=tokenData)

    @debugLogger
    def bulkCreate(self, objListParams: List[dict], token: str = ""):
        objList = []
        exceptions = []
        for objListParamsItem in objListParams:
            try:
                DomainModelAttributeValidator.validate(
                    domainModelObject=self._constructObject(skipValidation=True), attributeDictionary=objListParamsItem
                )
                objList.append(
                    self._constructObject(
                        id=objListParamsItem["standard_equipment_id"],
                        name=objListParamsItem["name"],
                        standardEquipmentCategoryId=objListParamsItem["standard_equipment_category_id"],
                        standardEquipmentCategoryGroupId=objListParamsItem["standard_equipment_category_group_id"],
                        manufacturerId=objListParamsItem["manufacturer_id"],
                        equipmentModelId=objListParamsItem["equipment_model_id"],
                    )
                )
            except DomainModelException as e:
                exceptions.append({"reason": {"message": e.message, "code": e.code}})
        _tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            self._standardEquipmentService.bulkCreate(objList=objList)
            if len(exceptions) > 0:
                raise ProcessBulkDomainException(messages=exceptions)
        except DomainModelException as e:
            exceptions.append({"reason": {"message": e.message, "code": e.code}})
            raise ProcessBulkDomainException(messages=exceptions)

    @debugLogger
    def bulkDelete(self, objListParams: List[dict], token: str = ""):
        objList = []
        exceptions = []
        for objListParamsItem in objListParams:
            try:
                DomainModelAttributeValidator.validate(
                    domainModelObject=self._constructObject(skipValidation=True), attributeDictionary=objListParamsItem
                )
                objList.append(
                    self._constructObject(id=objListParamsItem["standard_equipment_id"], skipValidation=True)
                )
            except DomainModelException as e:
                exceptions.append({"reason": {"message": e.message, "code": e.code}})
        _tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            self._standardEquipmentService.bulkDelete(objList=objList)
            if len(exceptions) > 0:
                raise ProcessBulkDomainException(messages=exceptions)
        except DomainModelException as e:
            exceptions.append({"reason": {"message": e.message, "code": e.code}})
            raise ProcessBulkDomainException(messages=exceptions)

    @debugLogger
    def bulkUpdate(self, objListParams: List[dict], token: str = ""):
        objList = []
        exceptions = []
        for objListParamsItem in objListParams:
            try:
                DomainModelAttributeValidator.validate(
                    domainModelObject=self._constructObject(skipValidation=True), attributeDictionary=objListParamsItem
                )
                oldObject: StandardEquipment = self._repo.standardEquipmentById(
                    id=objListParamsItem["standard_equipment_id"]
                )
                newObject = self._constructObject(
                    id=objListParamsItem["standard_equipment_id"],
                    name=objListParamsItem["name"] if "name" in objListParamsItem else None,
                    standardEquipmentCategoryId=objListParamsItem["standard_equipment_category_id"]
                    if "standard_equipment_category_id" in objListParamsItem
                    else None,
                    standardEquipmentCategoryGroupId=objListParamsItem["standard_equipment_category_group_id"]
                    if "standard_equipment_category_group_id" in objListParamsItem
                    else None,
                    manufacturerId=objListParamsItem["manufacturer_id"]
                    if "manufacturer_id" in objListParamsItem
                    else None,
                    equipmentModelId=objListParamsItem["equipment_model_id"]
                    if "equipment_model_id" in objListParamsItem
                    else None,
                    _sourceObject=oldObject,
                )
                objList.append(
                    (newObject, oldObject),
                )
            except DomainModelException as e:
                exceptions.append({"reason": {"message": e.message, "code": e.code}})
        _tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            self._standardEquipmentService.bulkUpdate(objList=objList)
            if len(exceptions) > 0:
                raise ProcessBulkDomainException(messages=exceptions)
        except DomainModelException as e:
            exceptions.append({"reason": {"message": e.message, "code": e.code}})
            raise ProcessBulkDomainException(messages=exceptions)

    @debugLogger
    def standardEquipmentById(self, id: str, token: str = None) -> StandardEquipment:
        standardEquipment = self._repo.standardEquipmentById(id=id)
        TokenService.tokenDataFromToken(token=token)
        return standardEquipment

    @debugLogger
    def standardEquipments(
        self,
        resultFrom: int = 0,
        resultSize: int = 100,
        order: List[dict] = None,
        token: str = None,
    ) -> dict:
        tokenData = TokenService.tokenDataFromToken(token=token)
        return self._standardEquipmentService.standardEquipments(
            tokenData=tokenData,
            resultFrom=resultFrom,
            resultSize=resultSize,
            order=order,
        )

    @debugLogger
    def _constructObject(self, *args, **kwargs) -> StandardEquipment:
        kwargs[BaseApplicationService.APPLICATION_SERVICE_CLASS] = StandardEquipment
        return super()._constructObject(*args, **kwargs)
