"""
The file is generated by scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from src.application.BaseApplicationService import BaseApplicationService
from src.domain_model.project.standard_equipment.standard_category.StandardEquipmentCategory import (
    StandardEquipmentCategory,
)
from src.domain_model.project.standard_equipment.standard_category.StandardEquipmentCategoryRepository import (
    StandardEquipmentCategoryRepository,
)
from src.domain_model.project.standard_equipment.standard_category.StandardEquipmentCategoryService import (
    StandardEquipmentCategoryService,
)
from src.domain_model.resource.exception.DomainModelException import DomainModelException
from src.domain_model.resource.exception.ProcessBulkDomainException import ProcessBulkDomainException
from src.domain_model.resource.exception.UpdateStandardEquipmentCategoryFailedException import (
    UpdateStandardEquipmentCategoryFailedException,
)
from src.domain_model.token.TokenService import TokenService
from src.domain_model.util.DomainModelAttributeValidator import DomainModelAttributeValidator
from src.resource.common.Util import Util
from src.resource.logging.decorator import debugLogger


class StandardEquipmentCategoryApplicationService(BaseApplicationService):
    def __init__(
        self,
        repo: StandardEquipmentCategoryRepository,
        standardEquipmentCategoryService: StandardEquipmentCategoryService,
    ):
        self._repo = repo
        self._standardEquipmentCategoryService = standardEquipmentCategoryService

    @debugLogger
    def newId(self):
        return StandardEquipmentCategory.createFrom(skipValidation=True).id()

    @debugLogger
    def createStandardEquipmentCategory(self, token: str = None, objectOnly: bool = False, **kwargs):
        obj: StandardEquipmentCategory = self._constructObject(**kwargs)
        tokenData = TokenService.tokenDataFromToken(token=token)
        return self._standardEquipmentCategoryService.createStandardEquipmentCategory(
            obj=obj, objectOnly=objectOnly, tokenData=tokenData
        )

    @debugLogger
    def updateStandardEquipmentCategory(self, token: str = None, **kwargs):
        tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            oldObject: StandardEquipmentCategory = self._repo.standardEquipmentCategoryById(id=kwargs["id"])
            obj: StandardEquipmentCategory = self._constructObject(_sourceObject=oldObject, **kwargs)
            self._standardEquipmentCategoryService.updateStandardEquipmentCategory(
                oldObject=oldObject, newObject=obj, tokenData=tokenData
            )
        except Exception as e:
            raise UpdateStandardEquipmentCategoryFailedException(message=str(e))

    @debugLogger
    def deleteStandardEquipmentCategory(self, id: str, token: str = None):
        tokenData = TokenService.tokenDataFromToken(token=token)
        obj = self._repo.standardEquipmentCategoryById(id=id)
        self._standardEquipmentCategoryService.deleteStandardEquipmentCategory(obj=obj, tokenData=tokenData)

    @debugLogger
    def bulkCreate(self, objListParams: List[dict], token: str = ""):
        objList = []
        exceptions = []
        for objListParamsItem in objListParams:
            try:
                DomainModelAttributeValidator.validate(
                    domainModelObject=self._constructObject(skipValidation=True), attributeDictionary=objListParamsItem
                )
                objList.append(
                    self._constructObject(
                            **Util.snakeCaseToLowerCameCaseDict(
                            objListParamsItem, keyReplacements=[{"source": "standard_equipment_category_id", "target": "id"}]
                        )
                    )
                )
            except DomainModelException as e:
                exceptions.append({"reason": {"message": e.message, "code": e.code}})
        _tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            self._standardEquipmentCategoryService.bulkCreate(objList=objList)
            if len(exceptions) > 0:
                raise ProcessBulkDomainException(messages=exceptions)
        except DomainModelException as e:
            exceptions.append({"reason": {"message": e.message, "code": e.code}})
            raise ProcessBulkDomainException(messages=exceptions)

    @debugLogger
    def bulkDelete(self, objListParams: List[dict], token: str = ""):
        objList = []
        exceptions = []
        for objListParamsItem in objListParams:
            try:
                DomainModelAttributeValidator.validate(
                    domainModelObject=self._constructObject(skipValidation=True), attributeDictionary=objListParamsItem
                )
                objList.append(
                    self._constructObject(id=objListParamsItem["standard_equipment_category_id"], skipValidation=True)
                )
            except DomainModelException as e:
                exceptions.append({"reason": {"message": e.message, "code": e.code}})
        _tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            self._standardEquipmentCategoryService.bulkDelete(objList=objList)
            if len(exceptions) > 0:
                raise ProcessBulkDomainException(messages=exceptions)
        except DomainModelException as e:
            exceptions.append({"reason": {"message": e.message, "code": e.code}})
            raise ProcessBulkDomainException(messages=exceptions)

    @debugLogger
    def bulkUpdate(self, objListParams: List[dict], token: str = ""):
        objList = []
        exceptions = []
        for objListParamsItem in objListParams:
            try:
                DomainModelAttributeValidator.validate(
                    domainModelObject=self._constructObject(skipValidation=True), attributeDictionary=objListParamsItem
                )
                oldObject: StandardEquipmentCategory = self._repo.standardEquipmentCategoryById(
                    id=objListParamsItem["standard_equipment_category_id"]
                )
                newObject = self._constructObject(
                    **Util.snakeCaseToLowerCameCaseDict(
                        objListParamsItem, keyReplacements=[{"source": "standard_equipment_category_id", "target": "id"}]
                    ),
                    _sourceObject=oldObject,
                )
                objList.append(
                    (newObject, oldObject),
                )
            except DomainModelException as e:
                exceptions.append({"reason": {"message": e.message, "code": e.code}})
        _tokenData = TokenService.tokenDataFromToken(token=token)
        try:
            self._standardEquipmentCategoryService.bulkUpdate(objList=objList)
            if len(exceptions) > 0:
                raise ProcessBulkDomainException(messages=exceptions)
        except DomainModelException as e:
            exceptions.append({"reason": {"message": e.message, "code": e.code}})
            raise ProcessBulkDomainException(messages=exceptions)

    @debugLogger
    def standardEquipmentCategoryById(self, id: str, token: str = None) -> StandardEquipmentCategory:
        standardEquipmentCategory = self._repo.standardEquipmentCategoryById(id=id)
        TokenService.tokenDataFromToken(token=token)
        return standardEquipmentCategory

    @debugLogger
    def standardEquipmentCategories(
        self,
        resultFrom: int = 0,
        resultSize: int = 100,
        order: List[dict] = None,
        token: str = None,
    ) -> dict:
        tokenData = TokenService.tokenDataFromToken(token=token)
        return self._standardEquipmentCategoryService.standardEquipmentCategories(
            tokenData=tokenData,
            resultFrom=resultFrom,
            resultSize=resultSize,
            order=order,
        )

    @debugLogger
    def _constructObject(self, *args, **kwargs) -> StandardEquipmentCategory:
        kwargs[BaseApplicationService.APPLICATION_SERVICE_CLASS] = StandardEquipmentCategory
        return super()._constructObject(*args, **kwargs)
