"""
The file is generated by scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""


from abc import ABC, abstractmethod

from src.domain_model.project.building.Building import Building


class BuildingRepository(ABC):
    @abstractmethod
    def save(self, obj: Building):
        """Save building

        Args:
            obj (Building): The building that needs to be saved

        """
