"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""


from src.port_adapter.messaging.listener.common.handler.lookup.daily_check_procedure.DeleteDailyCheckProcedureOperationHandler import \
    DeleteDailyCheckProcedureOperationHandler as Handler


class DeleteDailyCheckProcedureOperationHandler(Handler):
    pass
